const converted = {
  "p,div": { margin: "0", padding: "0" },
  p: { margin: "var(--ds-space-150, 12px) 0 0 0" },
  a: { color: "var(--ds-link, #0052CC)", textDecoration: "none" },
  "a:hover": { color: "var(--ds-link, #0065FF)", textDecoration: "underline" },
  "a:active": { color: "var(--ds-link-pressed, #0747A6)" },
  "p:first-child": { marginTop: "0" },
  button: { fontFamily: "inherit" },
  "._2rko12b0": { borderRadius: "var(--ds-radius-small,4px)" },
  "._19itglyw": { border: "none" },
  "._nd5l19l3": { gridArea: "interactive" },
  "._1r04ze3t": { inset: "var(--ds-space-0,0)" },
  "._zulpv77o": { gap: "var(--ds-space-025,2px)" },
  "._11c82smr": {
    font:
      'var(--ds-font-body,normal 400 14px/20px ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",Ubuntu,"Helvetica Neue",sans-serif)'
  },
  "._nd5l17zh": { gridArea: "elem-before" },
  "._nd5l16dh": { gridArea: "elem-after" },
  "._zulp1b66": { gap: "var(--ds-space-050,4px)" },
  "._2rkofajl": { borderRadius: "var(--ds-radius-small,3px)" },
  "._v5649dqc": { transition: "background 0.1s ease-out" },
  "._v564g17y": { transition: "opacity 0.3s" },
  "._19itidpf": { border: "0px" },
  "._11c81vhk": {
    font:
      'var(--ds-font-heading-xxsmall,normal 600 9pt/1pc ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",Ubuntu,"Helvetica Neue",sans-serif)'
  },
  "._1h6d1l7x": { borderColor: "var(--ds-border,#0b120e24)" },
  "._189ee4h9": { borderWidth: "var(--ds-border-width,1px)" },
  "._1dqonqa1": { borderStyle: "solid" },
  "._yyhyjvu9": { gridColumn: "1 / -1" },
  "._1ii7kb7n": { gridRow: "1" },
  "._189eidpf": { borderWidth: "0px" },
  "._1rjcv77o": { paddingBlock: "var(--ds-space-025,2px)" },
  "._18zr12x7": { paddingInline: "var(--ds-space-075,6px)" },
  "._1rjcu2gc": { paddingBlock: "var(--ds-space-100,8px)" },
  "._10m98stt": { scrollMarginInline: "750pt" },
  "._1e0c116y": { display: "inline-flex" },
  "._s7n4nkob": { verticalAlign: "middle" },
  "._1e0c1txw": { display: "flex" },
  "._1bah1h6o": { justifyContent: "center" },
  "._1bsbnklw": { width: "20pc" },
  "._bfhkvuon": { backgroundColor: "var(--ds-surface,#fff)" },
  "._16jlkb7n": { flexGrow: 1 },
  "._1o9zkb7n": { flexShrink: 1 },
  "._i0dlf1ug": { flexBasis: "0%" },
  "._1reo1wug": { overflowX: "auto" },
  "._18m91wug": { overflowY: "auto" },
  "._1q51utpp": { paddingBlockStart: "var(--ds-space-150,9pt)" },
  "._y4tiutpp": { paddingInlineEnd: "var(--ds-space-150,9pt)" },
  "._85i5utpp": { paddingBlockEnd: "var(--ds-space-150,9pt)" },
  "._bozgutpp": { paddingInlineStart: "var(--ds-space-150,9pt)" },
  "._vchhusvi": { boxSizing: "border-box" },
  "._1e0c11p5": { display: "grid" },
  "._yv0e7dup": {
    gridTemplateColumns:
      "minmax(0px, auto) 1fr minmax(0px, auto) minmax(0px, auto)"
  },
  "._2z05hkll": { gridTemplateRows: "1fr" },
  "._1lmcu4vt": {
    gridTemplateAreas: '"elem-before interactive elem-after actions"'
  },
  "._1ul9t9kd": { minWidth: "72px" },
  "._4t3iviql": { height: "2rem" },
  "._4cvr1h6o": { alignItems: "center" },
  "._uiztglyw": { userSelect: "none" },
  "._syazazsu": { color: "var(--ds-text-subtle,#505258)" },
  "._1yyu1j28": { "--notch-color": "transparent" },
  "._91ju1txw": { "--elem-after-display": "flex" },
  "._uomdidpf": { "--actions-on-hover-opacity": "0" },
  "._pmxpidpf": { "--actions-on-hover-width": "0" },
  "._db80idpf": { "--actions-on-hover-padding": "0" },
  "._uomdkb7n": { "--actions-on-hover-opacity": "1" },
  "._pmxp1wug": { "--actions-on-hover-width": "auto" },
  "._db801b66": { "--actions-on-hover-padding": "var(--ds-space-050,4px)" },
  "._kqswh2mm": { position: "relative" },
  "._yv0enbh3": { gridTemplateColumns: "subgrid" },
  "._2z05nbh3": { gridTemplateRows: "subgrid" },
  "._y4ti1b66": { paddingInlineEnd: "var(--ds-space-050,4px)" },
  "._bozg1b66": { paddingInlineStart: "var(--ds-space-050,4px)" },
  "._1q511b66": { paddingBlockStart: "var(--ds-space-050,4px)" },
  "._85i51b66": { paddingBlockEnd: "var(--ds-space-050,4px)" },
  "._bfhk1j28": { backgroundColor: "transparent" },
  "._y3gnv2br": { textAlign: "start" },
  "._14iu13ro:active:not(:disabled)": {
    backgroundColor: "var(--ds-surface-pressed,#dddee1)"
  },
  "._1cykglyw": { "--drag-handle-display": "none" },
  "._r06hglyw": { appearance: "none" },
  "._80omtlke": { cursor: "pointer" },
  "._ymio1r31:focus:not(:focus-visible)": { outlineColor: "currentcolor" },
  "._ypr0glyw:focus:not(:focus-visible)": { outlineStyle: "none" },
  "._zcxs1o36:focus:not(:focus-visible)": { outlineWidth: "medium" },
  "._2lx21bp4": { flexDirection: "column" },
  "._ae4v1h6o": { alignContent: "center" },
  "._kqswstnw": { position: "absolute" },
  "._1reo15vq": { overflowX: "hidden" },
  "._18m915vq": { overflowY: "hidden" },
  "._1ul91c9m": { minWidth: "1ch" },
  "._bozg12x7": { paddingInlineStart: "var(--ds-space-075,6px)" },
  "._19pkidpf": { marginTop: "0px" },
  "._2hwxidpf": { marginRight: "0px" },
  "._otyridpf": { marginBottom: "0px" },
  "._18u0idpf": { marginLeft: "0px" },
  "._1i4qfg65": { overflowWrap: "anywhere" },
  "._y3gn1h6o": { textAlign: "center" },
  "._1e0ccj1k": { display: "-webkit-box" },
  "._sudp1e54": { WebkitBoxOrient: "vertical" },
  "._1nmz9jpi": { wordBreak: "break-all" },
  "._syaz15cr": { color: "var(--ds-text-inverse,#fff)" },
  "._syaz1rpy": { color: "var(--ds-text-subtlest,#6b6e76)" },
  "._k48p1wq8": { fontWeight: "var(--ds-font-weight-medium,500)" },
  "._1o9zidpf": { flexShrink: 0 },
  "._1bsb1tcg": { width: "24px" },
  "._4t3i1tcg": { height: "24px" },
  "._vchh1ntv": { boxSizing: "content-box" },
  "._18ukglyw:not(:has(button, a))": { pointerEvents: "none" },
  "._1e0c1o8l": { display: "inline-block" },
  "._vwz4kb7n": { lineHeight: 1 },
  "._y4ti1igz": {
    paddingInlineEnd: "var(--ds--button--new-icon-padding-end,0)"
  },
  "._bozg1mb9": {
    paddingInlineStart: "var(--ds--button--new-icon-padding-start,0)"
  },
  "._vwz4utpp": { lineHeight: "var(--ds-space-150,9pt)" },
  "._syaz1r31": { color: "currentcolor" },
  "._lcxvglyw": { pointerEvents: "none" },
  "._s7n4yfq0": { verticalAlign: "bottom" },
  "._1bsbutpp": { width: "var(--ds-space-150,9pt)" },
  "._4t3iutpp": { height: "var(--ds-space-150,9pt)" },
  "._1bsbpxbi": { width: "var(--ds-space-200,1pc)" },
  "._4t3ipxbi": { height: "var(--ds-space-200,1pc)" },
  "._tzy4pnc3": { opacity: "var(--actions-on-hover-opacity)" },
  "._1bsbty16": { width: "var(--actions-on-hover-width)" },
  "._y4tidria": { paddingInlineEnd: "var(--actions-on-hover-padding)" },
  "._p12f1osq": { maxWidth: "100%" },
  "._4cvr1q9y": { alignItems: "baseline" },
  "._gy1p1b66": { columnGap: "var(--ds-space-050,4px)" },
  "._4bfu1r31": { textDecorationColor: "currentcolor" },
  "._1hmsglyw": { textDecorationLine: "none" },
  "._ajmmnqa1": { textDecorationStyle: "solid" },
  "._4t3i1k8s": { height: "1.5rem" },
  "._y4tize3t": { paddingInlineEnd: "var(--ds-space-0,0)" },
  "._bozgze3t": { paddingInlineStart: "var(--ds-space-0,0)" },
  "._1bsb1k8s": { width: "1.5rem" },
  "._1e02ze3t": { insetInlineStart: "var(--ds-space-0,0)" },
  "._bfhkqtfy": {
    backgroundColor: "var(--ds-background-neutral-subtle,transparent)"
  },
  "._o5721q9c": { whiteSpace: "nowrap" },
  "._16jlidpf": { flexGrow: 0 },
  "._1wpz1h6o": { alignSelf: "center" },
  "._1wybidpf": { fontSize: "0px" },
  "._vwz4idpf": { lineHeight: 0 },
  "._ca0qidpf": { paddingTop: "0px" },
  "._u5f3idpf": { paddingRight: "0px" },
  "._n3tdidpf": { paddingBottom: "0px" },
  "._19bvidpf": { paddingLeft: "0px" },
  "._1bsbt94y": { width: "1px" },
  "._4t3it94y": { height: "1px" },
  "._ogto7mnp": { clip: "rect(1px, 1px, 1px, 1px)" },
  "._1e0c13yo": { display: "var(--elem-after-display)" },
  "._1mmiglyw": { "--expandable-chevron-display": "none" },
  "._165n1bgi": { "--expandable-provided-elembefore-display": "contents" },
  "._b31z1txw:has(:focus-visible)": { "--expandable-chevron-display": "flex" },
  "._12xsglyw:has(:focus-visible)": {
    "--expandable-provided-elembefore-display": "none"
  },
  "._1e0ciw0t": { display: "var(--expandable-chevron-display)" },
  "._1e0c1xb2": { display: "var(--expandable-provided-elembefore-display)" },
  "._bozg1crf": { paddingInlineStart: "9pt" },
  "._1p1d1dk0": { textTransform: "capitalize" },
  "._1hms8stv": { textDecorationLine: "underline" },
  "._152t1ssb": { insetBlockStart: "50%" },
  "._1bsbyh40": { width: "2px" },
  "._4t3i1crf": { height: "9pt" },
  "._t9ec1i34": { transform: "translateY(-50%)" },
  "._bfhk1o0g": { backgroundColor: "var(--notch-color)" },
  "._1bsbgktf": { width: "20px" },
  "._4t3igktf": { height: "20px" },
  "._1e0c1i3c": { display: "var(--drag-handle-display,none)" },
  "._152tidpf": { insetBlockStart: "0px" },
  "._u7coidpf": { insetBlockEnd: "0px" },
  "._1e02idpf": { insetInlineStart: "0px" },
  "._ahbqxmi2": { marginInlineStart: "var(--ds-space-negative-150,-9pt)" },
  "._1053azsu:visited": { color: "var(--ds-text-subtle,#505258)" },
  "._1a3b1r31:focus": { textDecorationColor: "currentcolor" },
  "._4fprglyw:focus": { textDecorationLine: "none" },
  "._5goinqa1:focus": { textDecorationStyle: "solid" },
  "._f8pjazsu:focus": { color: "var(--ds-text-subtle,#505258)" },
  "._irr319i6:hover": { backgroundColor: "var(--ds-surface-hovered,#f0f1f2)" },
  "._g4kikb7n:hover": { "--actions-on-hover-opacity": "1" },
  "._ynyi1wug:hover": { "--actions-on-hover-width": "auto" },
  "._v4o21b66:hover": {
    "--actions-on-hover-padding": "var(--ds-space-050,4px)"
  },
  "._x0kw1txw:hover": { "--drag-handle-display": "flex" },
  "._11om6b4r:hover": { animationName: "k1xyysw3" },
  "._7psyru3m:hover": { animationDuration: "0s" },
  "._1uy01amc:hover": { animationDelay: "0.8s" },
  "._bir2q7pw:hover": { animationFillMode: "forwards" },
  "._14mj1kw7::after": { borderRadius: "inherit" },
  "._9v7aze3t::after": { inset: "var(--ds-space-0,0)" },
  "._1tv3nqa1::after": { borderStyle: "solid" },
  "._39yqe4h9::after": { borderWidth: "var(--ds-border-width,1px)" },
  "._11fnglyw::after": { pointerEvents: "none" },
  "._18postnw::after": { position: "absolute" },
  "._9oik1r31:hover": { textDecorationColor: "currentcolor" },
  "._1bnxglyw:hover": { textDecorationLine: "none" },
  "._jf4cnqa1:hover": { textDecorationStyle: "solid" },
  "._30l3azsu:hover": { color: "var(--ds-text-subtle,#505258)" },
  "._irr34mfv:hover": {
    backgroundColor: "var(--ds-background-neutral-subtle-hovered,#091e4214)"
  },
  "._1vnl1txw:hover": { "--expandable-chevron-display": "flex" },
  "._p8btglyw:hover": { "--expandable-provided-elembefore-display": "none" },
  "._1nrm1r31:active": { textDecorationColor: "currentcolor" },
  "._c2waglyw:active": { textDecorationLine: "none" },
  "._1iohnqa1:active": { textDecorationStyle: "solid" },
  "._9h8hazsu:active": { color: "var(--ds-text-subtle,#505258)" },
  "._1di619qy:active": {
    backgroundColor: "var(--ds-background-neutral-subtle-pressed,#b3d4ff)"
  },
  "@media screen and (forced-colors: active)": {
    "._12va1onz": { color: "canvastext" },
    "._jcxd1r8n": { filter: "grayscale(1)" }
  },
  "@keyframes k1xyysw3": { "100%": { cursor: "grab" } }
}
