export const meta = {
  button: {
    namespace: "ui",
    label: "Button",
    inputs: [
      { name: "label", type: "string", label: "Label", defaultValue: "Button" },
      {
        name: "variant",
        type: "enum",
        label: "Variant",
        enum: ["solid", "subtle", "surface", "outline", "ghost", "plain"],
        // enum: ["default", "secondary", "destructive", "outline", "ghost", "link"],
        defaultValue: "solid",
      },
      {
        name: "size",
        type: "enum",
        label: "Size",
        enum: ["2xs", "xs", "sm", "md", "lg", "xl", "2xl"],
        // enum: ["default", "sm", "lg", "icon"],
        defaultValue: "default",
      },
      { name: "className", type: "string", label: "CSS Class", advanced: true },
      { name: "css", type: "object", label: "CSS Style", advanced: true },
    ],
    defaultProps: {
      label: "Button",
      variant: "solid",
      size: "md",
    },
  },
  "button-group": {
    namespace: "ui",
    label: "Button Group",
    inputs: [
      {
        name: "variant",
        type: "enum",
        enum: ["default", "destructive", "outline", "secondary", "ghost", "link"],
        defaultValue: "default",
        label: "Variant",
      },
      {
        name: "size",
        type: "enum",
        enum: ["default", "sm", "lg", "icon"],
        defaultValue: "default",
        label: "Size",
      },
      { name: "className", type: "string", label: "CSS Class" },
    ],
    defaultProps: {
      variant: "default",
      size: "default",
      buttons: [{ label: "Left" }, { label: "Middle" }, { label: "Right" }],
    },
  },
  div: {
    namespace: "ui",
    label: "Container (Deprecated)",
    inputs: [{ name: "className", type: "string", label: "CSS Class" }],
    defaultProps: {
      className: "p-2 sm:p-4 border border-dashed border-gray-300 rounded min-h-[100px]",
    },
  },
  html: {
    namespace: "ui",
    label: "HTML Content",
    inputs: [{ name: "html", type: "string", label: "HTML", description: "Raw HTML content" }],
  },
  icon: {
    namespace: "ui",
    label: "Icon",
    icon: "smile",
    category: "basic",
    inputs: [
      { name: "name", type: "string", label: "Icon Name", defaultValue: "smile" },
      { name: "size", type: "number", label: "Size (px)" },
      { name: "color", type: "string", label: "Color Class" },
      { name: "className", type: "string", label: "CSS Class" },
    ],
  },
  image: {
    namespace: "ui",
    label: "Image",
    icon: "image",
    category: "basic",
    inputs: [
      { name: "src", type: "string", label: "Source URL" },
      { name: "alt", type: "string", label: "Alt Text" },
      { name: "className", type: "string", label: "Classes" },
    ],
    defaultProps: {
      className: "max-w-full h-auto",
    },
  },
  "navigation-menu": {
    namespace: "ui",
    label: "Navigation Menu",
    inputs: [{ name: "className", type: "string", label: "CSS Class" }],
    defaultProps: {
      items: [
        { label: "Home", href: "/" },
        { label: "About", href: "/about" },
      ],
    },
  },
  pagination: {
    namespace: "ui",
    label: "Pagination",
    inputs: [
      { name: "currentPage", type: "number", label: "Current Page", defaultValue: 1 },
      { name: "totalPages", type: "number", label: "Total Pages", defaultValue: 10 },
      { name: "className", type: "string", label: "CSS Class" },
    ],
    defaultProps: {
      currentPage: 1,
      totalPages: 10,
    },
  },
  separator: {
    namespace: "ui",
    label: "Separator",
    inputs: [
      {
        name: "orientation",
        type: "enum",
        enum: ["horizontal", "vertical"],
        defaultValue: "horizontal",
        label: "Orientation",
      },
      { name: "className", type: "string", label: "CSS Class" },
    ],
    defaultProps: {
      orientation: "horizontal",
      className: "my-2 sm:my-4",
    },
  },
  span: {
    namespace: "ui",
    label: "Inline Container (Deprecated)",
    inputs: [{ name: "className", type: "string", label: "CSS Class" }],
    defaultProps: {
      className: "px-1.5 py-0.5 sm:px-2 sm:py-1",
    },
    defaultChildren: [{ type: "text", content: "Inline text" }],
  },
  text: {
    namespace: "ui",
    label: "Text",
    inputs: [{ name: "content", type: "string", label: "Content", required: true }],
    defaultProps: {
      content: "Text content",
    },
  },
  carousel: {},
  "data-table": {},
  "filter-builder": {},
  resizable: {},
  "scroll-area": {},
  table: {},
  alert: {},
  avatar: {},
  badge: {},
  breadcrumb: {},
  kbd: {},
  list: {},
  statistic: {},
  "tree-view": {},
  accordion: {},
  collapsible: {},
  "toggle-group": {},
  schema: {},
  loading: {},
  progress: {},
  skeleton: {},
  sonner: {},
  spinner: {},
  toast: {},
  toaster: {},
  calendar: {},
  checkbox: {},
  combobox: {},
  command: {},
  "date-picker": {},
  "file-upload": {},
  form: {},
  input: {},
  "input-otp": {},
  label: {},
  "radio-group": {},
  select: {},
  slider: {},
  switch: {},
  textarea: {},
  toggle: {},
  "aspect-ratio": {},
  card: {},
  container: {},
  flex: {},
  grid: {},
  page: {},
  semantic: {},
  stack: {},
  tabs: {},
  "header-bar": {},
  sidebar: {},
  "alert-dialog": {},
  "context-menu": {},
  dialog: {},
  drawer: {},
  "dropdown-menu": {},
  "hover-card": {},
  menubar: {},
  popover: {},
  sheet: {},
  tooltip: {},
  placeholders: {},
}