export const dimensionMap = {
  "100%": "100%",
  "size.100": "1rem",
  "size.200": "1.5rem",
  "size.300": "2rem",
  "size.400": "2.5rem",
  "size.500": "3rem",
  "size.600": "6rem",
  "size.1000": "12rem",
} as const

export const positiveSpaceMap = {
  "space.0": "0px",
  "space.025": "2px",
  "space.050": "4px",
  "space.075": "6px",
  "space.100": "8px",
  "space.150": "12px",
  "space.200": "16px",
  "space.250": "20px",
  "space.300": "24px",
  "space.400": "32px",
  "space.500": "40px",
  "space.600": "48px",
  "space.800": "64px",
  "space.1000": "80px",
}

export const negativeSpaceMap = {
  "space.negative.025": "-2px",
  "space.negative.050": "-4px",
  "space.negative.075": "-6px",
  "space.negative.100": "-8px",
  "space.negative.150": "-12px",
  "space.negative.200": "-16px",
  "space.negative.250": "-20px",
  "space.negative.300": "-24px",
  "space.negative.400": "-32px",
}

export const allSpaceMap: any = { ...positiveSpaceMap, ...negativeSpaceMap }

export const inverseColorMap = {
  "color.background.neutral.bold": "color.text.inverse",
  "color.background.neutral.bold.hovered": "color.text.inverse",
  "color.background.neutral.bold.pressed": "color.text.inverse",
  "color.background.selected.bold": "color.text.inverse",
  "color.background.selected.bold.hovered": "color.text.inverse",
  "color.background.selected.bold.pressed": "color.text.inverse",
  "color.background.brand.bold": "color.text.inverse",
  "color.background.brand.bold.hovered": "color.text.inverse",
  "color.background.brand.bold.pressed": "color.text.inverse",
  "color.background.brand.boldest": "color.text.inverse",
  "color.background.brand.boldest.hovered": "color.text.inverse",
  "color.background.brand.boldest.pressed": "color.text.inverse",
  "color.background.danger.bold": "color.text.inverse",
  "color.background.danger.bold.hovered": "color.text.inverse",
  "color.background.danger.bold.pressed": "color.text.inverse",
  "color.background.warning.bold": "color.text.warning.inverse",
  "color.background.warning.bold.hovered": "color.text.warning.inverse",
  "color.background.warning.bold.pressed": "color.text.warning.inverse",
  "color.background.success.bold": "color.text.inverse",
  "color.background.success.bold.hovered": "color.text.inverse",
  "color.background.success.bold.pressed": "color.text.inverse",
  "color.background.discovery.bold": "color.text.inverse",
  "color.background.discovery.bold.hovered": "color.text.inverse",
  "color.background.discovery.bold.pressed": "color.text.inverse",
  "color.background.information.bold": "color.text.inverse",
  "color.background.information.bold.hovered": "color.text.inverse",
  "color.background.information.bold.pressed": "color.text.inverse",
} as const

export const opacityMap = {
  "opacity.disabled": 0.4,
  "opacity.loading": 0.2,
} as const

export const shadowMap = {
  "elevation.shadow.overflow": "0px 0px 8px #091e423f, 0px 0px 1px #091e424f",
  "elevation.shadow.overflow.perimeter": "#091e421f",
  "elevation.shadow.overflow.spread": "#091e4229",
  "elevation.shadow.overlay": "0px 8px 12px #091e423f, 0px 0px 1px #091e424f",

  "elevation.shadow.raised": "0px 1px 1px #091e423f, 0px 0px 1px #091e4221",
} as const

export const surfaceColorMap = {
  "elevation.surface": "#FFFFFF",
  "elevation.surface.hovered": "#FAFBFC",
  "elevation.surface.pressed": "#F4F5F7",
  "elevation.surface.overlay": "#FFFFFF",
  "elevation.surface.overlay.hovered": "#FAFBFC",
  "elevation.surface.overlay.pressed": "#F4F5F7",
  "elevation.surface.raised": "#FFFFFF",
  "elevation.surface.raised.hovered": "#FAFBFC",
  "elevation.surface.raised.pressed": "#F4F5F7",
  "elevation.surface.sunken": "#F4F5F7",
} as const

export const borderColorMap = {
  "color.border": "#091e4221",
  "color.border.accent.lime": "#6A9A23",
  "color.border.accent.red": "#FF5630",
  "color.border.accent.orange": "#D94008",
  "color.border.accent.yellow": "#FFAB00",
  "color.border.accent.green": "#36B37E",
  "color.border.accent.teal": "#00B8D9",
  "color.border.accent.blue": "#0065FF",
  "color.border.accent.purple": "#6554C0",
  "color.border.accent.magenta": "#CD519D",
  "color.border.accent.gray": "#5E6C84",
  "color.border.disabled": "#FAFBFC",
  "color.border.focused": "#2684FF",
  "color.border.input": "#FAFBFC",
  "color.border.inverse": "#FFFFFF",
  "color.border.selected": "#0052CC",
  "color.border.brand": "#0052CC",
  "color.border.danger": "#FF5630",
  "color.border.warning": "#FFC400",
  "color.border.success": "#00875A",
  "color.border.discovery": "#998DD9",
  "color.border.information": "#0065FF",
  "color.border.bold": "#344563",
} as const

export const backgroundColorMap: any = {
  "color.background.accent.lime.subtlest": "#EEFBDA",
  "color.background.accent.lime.subtlest.hovered": "#D3F1A7",
  "color.background.accent.lime.subtlest.pressed": "#B3DF72",
  "color.background.accent.lime.subtler": "#D3F1A7",
  "color.background.accent.lime.subtler.hovered": "#B3DF72",
  "color.background.accent.lime.subtler.pressed": "#94C748",
  "color.background.accent.lime.subtle": "#94C748",
  "color.background.accent.lime.subtle.hovered": "#B3DF72",
  "color.background.accent.lime.subtle.pressed": "#D3F1A7",
  "color.background.accent.lime.bolder": "#5B7F24",
  "color.background.accent.lime.bolder.hovered": "#37471F",
  "color.background.accent.lime.bolder.pressed": "#37471F",
  "color.background.accent.red.subtlest": "#FF8F73",
  "color.background.accent.red.subtlest.hovered": "#FF7452",
  "color.background.accent.red.subtlest.pressed": "#FF5630",
  "color.background.accent.red.subtler": "#FF7452",
  "color.background.accent.red.subtler.hovered": "#FF5630",
  "color.background.accent.red.subtler.pressed": "#DE350B",
  "color.background.accent.red.subtle": "#DE350B",
  "color.background.accent.red.subtle.hovered": "#FF5630",
  "color.background.accent.red.subtle.pressed": "#FF7452",
  "color.background.accent.red.bolder": "#DE350B",
  "color.background.accent.red.bolder.hovered": "#FF5630",
  "color.background.accent.red.bolder.pressed": "#FF7452",
  "color.background.accent.orange.subtlest": "#F18D13",
  "color.background.accent.orange.subtlest.hovered": "#FEC57B",
  "color.background.accent.orange.subtlest.pressed": "#FFE2BD",
  "color.background.accent.orange.subtler": "#B65C02",
  "color.background.accent.orange.subtler.hovered": "#F18D13",
  "color.background.accent.orange.subtler.pressed": "#FEC57B",
  "color.background.accent.orange.subtle": "#5F3811",
  "color.background.accent.orange.subtle.hovered": "#974F0C",
  "color.background.accent.orange.subtle.pressed": "#B65C02",
  "color.background.accent.orange.bolder": "#43290F",
  "color.background.accent.orange.bolder.hovered": "#5F3811",
  "color.background.accent.orange.bolder.pressed": "#974F0C",
  "color.background.accent.yellow.subtlest": "#FFE380",
  "color.background.accent.yellow.subtlest.hovered": "#FFC400",
  "color.background.accent.yellow.subtlest.pressed": "#FFAB00",
  "color.background.accent.yellow.subtler": "#FFC400",
  "color.background.accent.yellow.subtler.hovered": "#FFAB00",
  "color.background.accent.yellow.subtler.pressed": "#FF991F",
  "color.background.accent.yellow.subtle": "#FF991F",
  "color.background.accent.yellow.subtle.hovered": "#FFAB00",
  "color.background.accent.yellow.subtle.pressed": "#FFC400",
  "color.background.accent.yellow.bolder": "#FF991F",
  "color.background.accent.yellow.bolder.hovered": "#FFAB00",
  "color.background.accent.yellow.bolder.pressed": "#FFC400",
  "color.background.accent.green.subtlest": "#79F2C0",
  "color.background.accent.green.subtlest.hovered": "#57D9A3",
  "color.background.accent.green.subtlest.pressed": "#36B37E",
  "color.background.accent.green.subtler": "#57D9A3",
  "color.background.accent.green.subtler.hovered": "#36B37E",
  "color.background.accent.green.subtler.pressed": "#00875A",
  "color.background.accent.green.subtle": "#00875A",
  "color.background.accent.green.subtle.hovered": "#36B37E",
  "color.background.accent.green.subtle.pressed": "#57D9A3",
  "color.background.accent.green.bolder": "#00875A",
  "color.background.accent.green.bolder.hovered": "#36B37E",
  "color.background.accent.green.bolder.pressed": "#57D9A3",
  "color.background.accent.teal.subtlest": "#79E2F2",
  "color.background.accent.teal.subtlest.hovered": "#00C7E6",
  "color.background.accent.teal.subtlest.pressed": "#00B8D9",
  "color.background.accent.teal.subtler": "#00C7E6",
  "color.background.accent.teal.subtler.hovered": "#00B8D9",
  "color.background.accent.teal.subtler.pressed": "#00A3BF",
  "color.background.accent.teal.subtle": "#00A3BF",
  "color.background.accent.teal.subtle.hovered": "#00B8D9",
  "color.background.accent.teal.subtle.pressed": "#00C7E6",
  "color.background.accent.teal.bolder": "#00A3BF",
  "color.background.accent.teal.bolder.hovered": "#00B8D9",
  "color.background.accent.teal.bolder.pressed": "#00C7E6",
  "color.background.accent.blue.subtlest": "#4C9AFF",
  "color.background.accent.blue.subtlest.hovered": "#2684FF",
  "color.background.accent.blue.subtlest.pressed": "#0065FF",
  "color.background.accent.blue.subtler": "#2684FF",
  "color.background.accent.blue.subtler.hovered": "#0065FF",
  "color.background.accent.blue.subtler.pressed": "#0052CC",
  "color.background.accent.blue.subtle": "#0052CC",
  "color.background.accent.blue.subtle.hovered": "#0065FF",
  "color.background.accent.blue.subtle.pressed": "#2684FF",
  "color.background.accent.blue.bolder": "#0052CC",
  "color.background.accent.blue.bolder.hovered": "#0065FF",
  "color.background.accent.blue.bolder.pressed": "#2684FF",
  "color.background.accent.purple.subtlest": "#998DD9",
  "color.background.accent.purple.subtlest.hovered": "#8777D9",
  "color.background.accent.purple.subtlest.pressed": "#6554C0",
  "color.background.accent.purple.subtler": "#8777D9",
  "color.background.accent.purple.subtler.hovered": "#6554C0",
  "color.background.accent.purple.subtler.pressed": "#5243AA",
  "color.background.accent.purple.subtle": "#5243AA",
  "color.background.accent.purple.subtle.hovered": "#6554C0",
  "color.background.accent.purple.subtle.pressed": "#8777D9",
  "color.background.accent.purple.bolder": "#5243AA",
  "color.background.accent.purple.bolder.hovered": "#6554C0",
  "color.background.accent.purple.bolder.pressed": "#8777D9",
  "color.background.accent.magenta.subtlest": "#FFECF8",
  "color.background.accent.magenta.subtlest.hovered": "#FDD0EC",
  "color.background.accent.magenta.subtlest.pressed": "#F797D2",
  "color.background.accent.magenta.subtler": "#FDD0EC",
  "color.background.accent.magenta.subtler.hovered": "#F797D2",
  "color.background.accent.magenta.subtler.pressed": "#E774BB",
  "color.background.accent.magenta.subtle": "#E774BB",
  "color.background.accent.magenta.subtle.hovered": "#F797D2",
  "color.background.accent.magenta.subtle.pressed": "#FDD0EC",
  "color.background.accent.magenta.bolder": "#AE4787",
  "color.background.accent.magenta.bolder.hovered": "#943D73",
  "color.background.accent.magenta.bolder.pressed": "#50253F",
  "color.background.accent.gray.subtlest": "#6B778C",
  "color.background.accent.gray.subtlest.hovered": "#5E6C84",
  "color.background.accent.gray.subtlest.pressed": "#505F79",
  "color.background.accent.gray.subtler": "#5E6C84",
  "color.background.accent.gray.subtler.hovered": "#505F79",
  "color.background.accent.gray.subtler.pressed": "#42526E",
  "color.background.accent.gray.subtle": "#505F79",
  "color.background.accent.gray.subtle.hovered": "#5E6C84",
  "color.background.accent.gray.subtle.pressed": "#6B778C",
  "color.background.accent.gray.bolder": "#42526E",
  "color.background.accent.gray.bolder.hovered": "#344563",
  "color.background.accent.gray.bolder.pressed": "#253858",
  "color.background.disabled": "#091e4289",
  "color.background.input": "#FAFBFC",
  "color.background.input.hovered": "#EBECF0",
  "color.background.input.pressed": "#FFFFFF",
  "color.background.inverse.subtle": "#00000029",
  "color.background.inverse.subtle.hovered": "#0000003D",
  "color.background.inverse.subtle.pressed": "#00000052",
  "color.background.neutral": "#DFE1E6",
  "color.background.neutral.hovered": "#091e4214",
  "color.background.neutral.pressed": "#B3D4FF",
  "color.background.neutral.subtle": "transparent",
  "color.background.neutral.subtle.hovered": "#091e4214",
  "color.background.neutral.subtle.pressed": "#B3D4FF",
  "color.background.neutral.bold": "#42526E",
  "color.background.neutral.bold.hovered": "#505F79",
  "color.background.neutral.bold.pressed": "#344563",
  "color.background.selected": "#DEEBFF",
  "color.background.selected.hovered": "#B3D4FF",
  "color.background.selected.pressed": "#4C9AFF",
  "color.background.selected.bold": "#0052CC",
  "color.background.selected.bold.hovered": "#2684FF",
  "color.background.selected.bold.pressed": "#0052CC",
  "color.background.brand.subtlest": "#B3D4FF",
  "color.background.brand.subtlest.hovered": "#DEEBFF",
  "color.background.brand.subtlest.pressed": "#4C9AFF",
  "color.background.brand.bold": "#0052CC",
  "color.background.brand.bold.hovered": "#0065FF",
  "color.background.brand.bold.pressed": "#0747A6",
  "color.background.brand.boldest": "#0747A6",
  "color.background.brand.boldest.hovered": "#0052CC",
  "color.background.brand.boldest.pressed": "#0747A6",
  "color.background.danger": "#FFEBE6",
  "color.background.danger.hovered": "#FFBDAD",
  "color.background.danger.pressed": "#FF8F73",
  "color.background.danger.subtler": "#FFBDAD",
  "color.background.danger.subtler.hovered": "#FF8F73",
  "color.background.danger.subtler.pressed": "#FF7452",
  "color.background.danger.bold": "#DE350B",
  "color.background.danger.bold.hovered": "#FF5630",
  "color.background.danger.bold.pressed": "#BF2600",
  "color.background.warning": "#FFFAE6",
  "color.background.warning.hovered": "#FFF0B3",
  "color.background.warning.pressed": "#FFE380",
  "color.background.warning.subtler": "#FFF0B3",
  "color.background.warning.subtler.hovered": "#FFE380",
  "color.background.warning.subtler.pressed": "#FFC400",
  "color.background.warning.bold": "#FFAB00",
  "color.background.warning.bold.hovered": "#FFC400",
  "color.background.warning.bold.pressed": "#FF991F",
  "color.background.success": "#E3FCEF",
  "color.background.success.hovered": "#ABF5D1",
  "color.background.success.pressed": "#79F2C0",
  "color.background.success.subtler": "#ABF5D1",
  "color.background.success.subtler.hovered": "#79F2C0",
  "color.background.success.subtler.pressed": "#57D9A3",
  "color.background.success.bold": "#00875A",
  "color.background.success.bold.hovered": "#57D9A3",
  "color.background.success.bold.pressed": "#00875A",
  "color.background.discovery": "#EAE6FF",
  "color.background.discovery.hovered": "#C0B6F2",
  "color.background.discovery.pressed": "#998DD9",
  "color.background.discovery.subtler": "#C0B6F2",
  "color.background.discovery.subtler.hovered": "#998DD9",
  "color.background.discovery.subtler.pressed": "#8777D9",
  "color.background.discovery.bold": "#5243AA",
  "color.background.discovery.bold.hovered": "#8777D9",
  "color.background.discovery.bold.pressed": "#5243AA",
  "color.background.information": "#DEEBFF",
  "color.background.information.hovered": "#B3D4FF",
  "color.background.information.pressed": "#4C9AFF",
  "color.background.information.subtler": "#B3D4FF",
  "color.background.information.subtler.hovered": "#4C9AFF",
  "color.background.information.subtler.pressed": "#2684FF",
  "color.background.information.bold": "#0052CC",
  "color.background.information.bold.hovered": "#2684FF",
  "color.background.information.bold.pressed": "#0052CC",
  "color.blanket": "#091e4289",
  "color.blanket.selected": "#388BFF14",
  "color.blanket.danger": "#EF5C4814",
  "color.skeleton": "#F4F5F7",
  "color.skeleton.subtle": "#091e420a",
  "elevation.surface": "#FFFFFF",
  "elevation.surface.hovered": "#FAFBFC",
  "elevation.surface.pressed": "#F4F5F7",
  "elevation.surface.overlay": "#FFFFFF",
  "elevation.surface.overlay.hovered": "#FAFBFC",
  "elevation.surface.overlay.pressed": "#F4F5F7",
  "elevation.surface.raised": "#FFFFFF",
  "elevation.surface.raised.hovered": "#FAFBFC",
  "elevation.surface.raised.pressed": "#F4F5F7",
  "elevation.surface.sunken": "#F4F5F7",
  "utility.elevation.surface.current": "#FFFFFF",
} as const

export const textColorMap = {
  "color.text": "#172B4D",
  "color.text.accent.lime": "#4C6B1F",
  "color.text.accent.lime.bolder": "#37471F",
  "color.text.accent.red": "#DE350B",
  "color.text.accent.red.bolder": "#BF2600",
  "color.text.accent.orange": "#F18D13",
  "color.text.accent.orange.bolder": "#B65C02",
  "color.text.accent.yellow": "#FF991F",
  "color.text.accent.yellow.bolder": "#FF8B00",
  "color.text.accent.green": "#00875A",
  "color.text.accent.green.bolder": "#006644",
  "color.text.accent.teal": "#00A3BF",
  "color.text.accent.teal.bolder": "#008DA6",
  "color.text.accent.blue": "#0052CC",
  "color.text.accent.blue.bolder": "#0747A6",
  "color.text.accent.purple": "#5243AA",
  "color.text.accent.purple.bolder": "#403294",
  "color.text.accent.magenta": "#E774BB",
  "color.text.accent.magenta.bolder": "#DA62AC",
  "color.text.accent.gray": "#505F79",
  "color.text.accent.gray.bolder": "#172B4D",
  "color.text.disabled": "#A5ADBA",
  "color.text.inverse": "#FFFFFF",
  "color.text.selected": "#0052CC",
  "color.text.brand": "#0065FF",
  "color.text.danger": "#DE350B",
  "color.text.danger.bolder": "#BF2600",
  "color.text.warning": "#974F0C",
  "color.text.warning.inverse": "#172B4D",
  "color.text.warning.bolder": "#974F0C",
  "color.text.success": "#006644",
  "color.text.success.bolder": "#006644",
  "color.text.discovery": "#403294",
  "color.text.discovery.bolder": "#403294",
  "color.text.information": "#0052CC",
  "color.text.information.bolder": "#0747A6",
  "color.text.subtlest": "#7A869A",
  "color.text.subtle": "#42526E",
  "color.link": "#0052CC",
  "color.link.pressed": "#0747A6",
  "color.link.visited": "#403294",
  "color.link.visited.pressed": "#403294",
} as const

export const fillMap = {
  "color.icon": "#505F79",
  "color.icon.accent.lime": "#6A9A23",
  "color.icon.accent.red": "#FF5630",
  "color.icon.accent.orange": "#D94008",
  "color.icon.accent.yellow": "#FFAB00",
  "color.icon.accent.green": "#36B37E",
  "color.icon.accent.teal": "#00B8D9",
  "color.icon.accent.blue": "#0065FF",
  "color.icon.accent.purple": "#6554C0",
  "color.icon.accent.magenta": "#CD519D",
  "color.icon.accent.gray": "#5E6C84",
  "color.icon.disabled": "#8993A4",
  "color.icon.inverse": "#FFFFFF",
  "color.icon.selected": "#0052CC",
  "color.icon.brand": "#0065FF",
  "color.icon.danger": "#DE350B",
  "color.icon.warning": "#FFC400",
  "color.icon.warning.inverse": "#253858",
  "color.icon.success": "#00875A",
  "color.icon.discovery": "#8777D9",
  "color.icon.information": "#0747A6",
  "color.icon.subtlest": "#6B778C",
  "color.icon.subtle": "#6B778C",
} as const

export const layerMap = {
  "1": 1,
  card: 100,
  navigation: 200,
  dialog: 300,
  layer: 400,
  blanket: 500,
  modal: 510,
  flag: 600,
  spotlight: 700,
  tooltip: 800,
} as const

export const borderWidthMap = {
  "border.width": "1px",
  "border.width.selected": "2px",
  "border.width.focused": "2px",
}

export const borderRadiusMap = {
  "radius.xsmall": "2px",
  "radius.small": "3px",
  "radius.medium": "6px",
  "radius.large": "8px",
  "radius.xlarge": "12px",
  "radius.xxlarge": "16px",
  "radius.full": "9999px",
  "radius.tile": "25%",
}

export const fontMap = {
  "font.body":
    'normal 400 14px/20px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Ubuntu, "Helvetica Neue", sans-serif',
  "font.body.UNSAFE_small":
    'normal 400 12px/16px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Ubuntu, "Helvetica Neue", sans-serif',
  "font.body.large":
    'normal 400 16px/24px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Ubuntu, "Helvetica Neue", sans-serif',
  "font.body.small":
    'normal 400 11px/16px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Ubuntu, "Helvetica Neue", sans-serif',
  "font.code": 'normal 400 0.875em/1 ui-monospace, Menlo, "Segoe UI Mono", "Ubuntu Mono", monospace',
  "font.heading.large":
    'normal 500 24px/28px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Ubuntu, "Helvetica Neue", sans-serif',
  "font.heading.medium":
    'normal 500 20px/24px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Ubuntu, "Helvetica Neue", sans-serif',
  "font.heading.small":
    'normal 600 16px/20px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Ubuntu, "Helvetica Neue", sans-serif',
  "font.heading.xlarge":
    'normal 600 29px/32px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Ubuntu, "Helvetica Neue", sans-serif',
  "font.heading.xsmall":
    'normal 600 14px/16px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Ubuntu, "Helvetica Neue", sans-serif',
  "font.heading.xxlarge":
    'normal 500 35px/40px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Ubuntu, "Helvetica Neue", sans-serif',
  "font.heading.xxsmall":
    'normal 600 12px/16px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Ubuntu, "Helvetica Neue", sans-serif',
  "font.metric.large":
    'normal 653 28px/32px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Ubuntu, "Helvetica Neue", sans-serif',
  "font.metric.medium":
    'normal 653 24px/28px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Ubuntu, "Helvetica Neue", sans-serif',
  "font.metric.small":
    'normal 653 16px/20px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Ubuntu, "Helvetica Neue", sans-serif',
}

export const fontWeightMap = {
  "font.weight.bold": "700",
  "font.weight.medium": "500",
  "font.weight.regular": "400",
  "font.weight.semibold": "600",
}

export const fontFamilyMap = {
  "font.family.body":
    'ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Ubuntu, "Helvetica Neue", sans-serif',
  "font.family.brand.body":
    '"Charlie Text", ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Ubuntu, "Helvetica Neue", sans-serif',
  "font.family.brand.heading":
    '"Charlie Display", ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Ubuntu, "Helvetica Neue", sans-serif',
  "font.family.code": 'ui-monospace, Menlo, "Segoe UI Mono", "Ubuntu Mono", monospace',
  "font.family.heading":
    'ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Ubuntu, "Helvetica Neue", sans-serif',
}

export const textSizeMap = {
  medium:
    'normal 400 14px/20px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Ubuntu, "Helvetica Neue", sans-serif',
  UNSAFE_small:
    'normal 400 12px/16px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Ubuntu, "Helvetica Neue", sans-serif',
  large:
    'normal 400 16px/24px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Ubuntu, "Helvetica Neue", sans-serif',
  small:
    'normal 400 11px/16px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Ubuntu, "Helvetica Neue", sans-serif',
}

export const textWeightMap = {
  bold: "700",
  medium: "500",
  regular: "400",
  semibold: "600",
}

export const metricTextSizeMap = {
  large:
    'normal 653 28px/32px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Ubuntu, "Helvetica Neue", sans-serif',
  medium:
    'normal 653 24px/28px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Ubuntu, "Helvetica Neue", sans-serif',
  small:
    'normal 653 16px/20px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Ubuntu, "Helvetica Neue", sans-serif',
}

export const spacingProperties = [
  // Used by Box
  "padding",
  "paddingBlock",
  "paddingBlockStart",
  "paddingBlockEnd",
  "paddingInline",
  "paddingInlineStart",
  "paddingInlineEnd",
  // Used by Inline and Stack
  "gap",
  "rowGap",
  "columnGap",
] as const


export const allTokens = {
  ...dimensionMap,
  ...allSpaceMap,
  ...inverseColorMap,
  ...opacityMap,
  ...shadowMap,
  ...surfaceColorMap,
  ...borderColorMap,
  ...backgroundColorMap,
  ...textColorMap,
  ...fillMap,
  ...layerMap,
  ...borderWidthMap,
  ...borderRadiusMap,
  ...fontMap,
  ...fontWeightMap,
  ...fontFamilyMap,
  ...textSizeMap,
  ...textWeightMap,
  ...metricTextSizeMap,
}

export const token = (key: keyof typeof allTokens) => {
  return allTokens[key]
}




