import { defineSlotRecipe } from "@chakra-ui/react"

export const appShellSlotRecipe = defineSlotRecipe({
  className: "app-shell",
  slots: [
    "root",
    "header",
    "main",
    "mainContainer",
    "footer",
    "bottom",
    "sidebarLeft",
    "sidePanelLeft",
    "sidebarRight",
    "sidePanelRight",
    "body",
    "canvas",
    "canvasTop",
    "canvasBottom",
    "resizeHandleRight",
    "resizeHandleLeft",
    "resizeHandleTop",
  ],
  base: {
    root: {
      "--floating-offset": "8px",
      "--header-height": "50px",
      "--footer-height": "30px",
      "--bottom-height": "150px",
      "--sidebar-left-width": "50px",
      "--side-panel-left-width": "200px",
      "--sidebar-right-width": "50px",
      "--side-panel-right-width": "200px",
      "--canvas-top-height": "40px",
      "--canvas-bottom-height": "200px",
      position: "relative",
      display: "flex",
      flexDirection: "column",
      width: "100%",
      height: "100%",
      bg: "bg.panel",
    },
    header: {
      borderBottom: "1px solid",
      borderBottomColor: "border",
      height: "var(--header-height)",
    },
    main: {
      flex: 1,
      display: "flex",
      flexDirection: "column",
    },
    mainContainer: {
      display: "flex",
      height: "100%",
      position: "relative",
    },
    footer: {
      h: "var(--footer-height)",
      borderTop: "1px solid",
      borderTopColor: "border",
    },
    bottom: {
      h: "var(--bottom-height)",
      borderTop: "1px solid",
      borderTopColor: "border",
      bg: "bg.panel",
      zIndex: 1,
    },
    sidebarLeft: {
      w: "var(--sidebar-left-width)",
      borderRight: "1px solid",
      borderRightColor: "border",
      h: "100%",
    },
    sidePanelLeft: {
      w: "var(--side-panel-left-width)",
      display: "flex",
      borderRight: "1px solid",
      borderRightColor: "border",
      h: "100%",
      bg: "bg.panel",
      zIndex: 1,
      position: "relative",
    },
    sidebarRight: {
      w: "var(--sidebar-right-width)",
      borderLeft: "1px solid",
      borderLeftColor: "border",
      h: "100%",
    },
    sidePanelRight: {
      w: "var(--side-panel-right-width)",
      borderLeft: "1px solid",
      borderLeftColor: "border",
      h: "100%",
      bg: "bg.panel",
      zIndex: 1,
      position: "relative",
    },
    body: {
      position: "relative",
      flex: 1,
      display: "flex",
      flexDirection: "column",
      h: "100%",
    },
    canvas: {
      flex: 1,
      bg: "bg.subtle",
      p: 4,
    },
    canvasTop: {
      h: "var(--canvas-top-height)",
      borderBottom: "1px solid",
      borderBottomColor: "border",
    },
    canvasBottom: {
      h: "var(--bottom-height)",
      borderTop: "1px solid",
      borderTopColor: "border",
      bg: "bg.panel",
      position: "relative",
    },
    // Resize handles
    resizeHandleRight: {
      position: "absolute",
      top: 0,
      right: 0,
      width: "6px",
      height: "100%",
      cursor: "ew-resize",
      zIndex: 10,
      bg: "transparent",
    },
    resizeHandleLeft: {
      position: "absolute",
      top: 0,
      left: 0,
      width: "6px",
      height: "100%",
      cursor: "ew-resize",
      zIndex: 10,
      bg: "transparent",
    },
    resizeHandleTop: {
      position: "absolute",
      top: 0,
      left: 0,
      width: "100%",
      height: "6px",
      cursor: "ns-resize",
      zIndex: 10,
      bg: "transparent",
    },
  },
  variants: {
    showHeader: { true: {}, false: { header: { display: "none" } } },
    showFooter: { true: {}, false: { footer: { display: "none" } } },
    showBottom: { true: {}, false: { bottom: { display: "none" } } },
    showSidebarLeft: { true: {}, false: { sidebarLeft: { display: "none" } } },
    showSidePanelLeft: { true: {}, false: { sidePanelLeft: { display: "none" } } },
    showSidebarRight: { true: {}, false: { sidebarRight: { display: "none" } } },
    showSidePanelRight: { true: {}, false: { sidePanelRight: { display: "none" } } },
    showCanvasTop: { true: {}, false: { canvasTop: { display: "none" } } },
    showCanvasBottom: { true: {}, false: { canvasBottom: { display: "none" } } },
    pinnedSidePanelLeft: {
      true: {},
      false: {
        sidePanelLeft: {
          position: "absolute",
          top: "var(--floating-offset)",
          bottom: "var(--floating-offset)",
          left: "calc(var(--sidebar-left-width) + var(--floating-offset))",
          border: "1px solid",
          borderColor: "border",
          borderRadius: "md",
          boxShadow: "xs",
        },
      },
    },
    pinnedSidePanelRight: {
      true: {},
      false: {
        sidePanelRight: {
          position: "absolute",
          top: "var(--floating-offset)",
          bottom: "var(--floating-offset)",
          right: "calc(var(--sidebar-right-width) + var(--floating-offset))",
          border: "1px solid",
          borderColor: "border",
          borderRadius: "md",
          boxShadow: "xs",
        },
      },
    },
    pinnedCanvasBottom: {
      true: {},
      false: {
        canvasBottom: {
          position: "absolute",
          left: "var(--floating-offset)",
          right: "var(--floating-offset)",
          bottom: "var(--floating-offset)",
          border: "1px solid",
          borderColor: "border",
          borderRadius: "md",
          boxShadow: "xs",
        },
      },
    },
    pinnedBottom: {
      true: {},
      false: {
        bottom: {
          position: "absolute",
          left: "var(--floating-offset)",
          right: "var(--floating-offset)",
          bottom: "var(--floating-offset)",
          border: "1px solid",
          borderColor: "border",
          borderRadius: "md",
          boxShadow: "xs",
        },
      },
    },
  },
  compoundVariants: [
    {
      pinnedBottom: false,
      showFooter: true,
      css: {
        bottom: {
          bottom: "calc(var(--footer-height) + var(--floating-offset))",
        },
      },
    },
    {
      pinnedBottom: false,
      showFooter: false,
      css: {
        bottom: {
          bottom: "var(--floating-offset)",
        },
      },
    },

    {
      pinnedSidePanelLeft: false,
      showSidebarLeft: true,
      css: {
        sidePanelLeft: {
          position: "absolute",
          top: "var(--floating-offset)",
          bottom: "var(--floating-offset)",
          left: "calc(var(--sidebar-left-width) + var(--floating-offset))",
        },
      },
    },
    {
      pinnedSidePanelLeft: false,
      showSidebarLeft: false,
      css: {
        sidePanelLeft: {
          position: "absolute",
          top: "var(--floating-offset)",
          bottom: "var(--floating-offset)",
          left: "var(--floating-offset)",
        },
      },
    },

    {
      pinnedSidePanelRight: false,
      showSidebarRight: true,
      css: {
        sidePanelRight: {
          position: "absolute",
          top: "var(--floating-offset)",
          bottom: "var(--floating-offset)",
          right: "calc(var(--sidebar-right-width) + var(--floating-offset))",
        },
      },
    },
    {
      pinnedSidePanelRight: false,
      showSidebarRight: false,
      css: {
        sidePanelRight: {
          position: "absolute",
          top: "var(--floating-offset)",
          bottom: "var(--floating-offset)",
          right: "var(--floating-offset)",
        },
      },
    },
  ],
  defaultVariants: {
    showHeader: true,
    showFooter: true,
    showBottom: true,
    showSidebarLeft: true,
    showSidePanelLeft: true,
    showSidebarRight: true,
    showSidePanelRight: true,
    showCanvasTop: true,
    showCanvasBottom: true,
    pinnedSidePanelLeft: true,
    pinnedSidePanelRight: true,
    pinnedCanvasBottom: true,
    pinnedBottom: true,
  },
})
