export { AvatarContext } from "./avatar-context"
export { AvatarFallback } from "./avatar-fallback"
export { AvatarImage } from "./avatar-image"
export { AvatarRoot } from "./avatar-root"
export { AvatarRootProvider } from "./avatar-root-provider"
export { avatarAnatomy } from "./avatar.anatomy"
export { useAvatar } from "./use-avatar"
export { useAvatarContext } from "./use-avatar-context"

export * as Avatar from "./avatar"
