const basicTreeData = {
  0: {
    json: [
      {
        id: "QHU7fTAyoL",
        name: "node3",
        path: { raw: "node3", segments: ["node3"] },
        class: "endpoint",
        kind: "Item",
        protocol: "Get",
        order: 1,
        expanded: false,
      },
    ],
  },
  1: {
    json: {
      name: "projecr2",
      class: "endpoint",
      kind: "Item",
      protocol: "Get",
      url: null,
      headers: [],
      pathParams: [],
      queryParams: [],
      body: null,
    },
    meta: { values: { url: ["undefined"] } },
  },
  3: {
    json: {
      name: "file1",
      class: "endpoint",
      kind: "Item",
      protocol: "Get",
      url: null,
      headers: [],
      pathParams: [],
      queryParams: [],
      body: null,
    },
    meta: { values: { url: ["undefined"] } },
  },
  4: {
    json: {
      name: "node3",
      class: "endpoint",
      kind: "Item",
      protocol: "Get",
      url: null,
      headers: [],
      pathParams: [],
      queryParams: [],
      body: null,
    },
    meta: { values: { url: ["undefined"] } },
  },
  5: {
    json: [
      {
        id: "nWaVbDeTgN",
        name: "folder2",
        path: { raw: "folder2", segments: ["folder2"] },
        class: "endpoint",
        kind: "Dir",
        protocol: null,
        order: 2,
        expanded: true,
      },
      {
        id: "rSNBPqNP85",
        name: "projecr2",
        path: { raw: "projecr2", segments: ["projecr2"] },
        class: "endpoint",
        kind: "Item",
        protocol: "Get",
        order: 1,
        expanded: false,
      },
      {
        id: "c4SmicCvJ1",
        name: "folder1",
        path: { raw: "folder2/folder1", segments: ["folder2", "folder1"] },
        class: "endpoint",
        kind: "Dir",
        protocol: null,
        order: 1,
        expanded: true,
      },
      {
        id: "9yuHeSkl9N",
        name: "file1",
        path: { raw: "folder2/folder1/file1", segments: ["folder2", "folder1", "file1"] },
        class: "endpoint",
        kind: "Item",
        protocol: "Get",
        order: 1,
        expanded: false,
      },
    ],
  },
  6: {
    json: [
      {
        id: "q9XtZFci7f",
        name: "New Project1",
        order: 1,
        expanded: true,
        branch: null,
        iconPath: null,
        archived: false,
      },
      { id: "Pod65Sax7E", name: "node2", order: 2, expanded: true, branch: null, iconPath: null, archived: false },
    ],
  },
}
