export default {
  "remix-config": {
    version: 2,
    baseUrl: "https://tokens.staging.remix.live",
    mode: "instance",
    services: {
      sso: "/sso",
      profile: "/profile",
      permissions: "/permissions",
      invite: "/invite",
      billing: "/billing",
      credits: "/credits",
      products: "/products",
      checkouts: "/checkouts",
      storage: "/storage",
      solcoder: "/ai/solcoder",
      completion: "/ai/completion",
      rag: "/ai/rag",
      audio: "/ai/audio",
      dappGenerator: "/ai/dapp-generator",
      figma: "/ai/figma",
      langchain: "/ai/langchain",
      langsmith: "/ai/langsmith",
      langfuse: "/ai/langfuse",
      aiUsage: "/ai-usage",
      mcp: "/mcp",
      corsProxy: "/endpoints/corsproxy",
      commonCorsProxy: "/endpoints/common-corsproxy",
      github: "/endpoints/github",
      gitHubLoginProxy: "/endpoints/github-login-proxy",
      ghfolderpull: "/endpoints/ghfolderpull",
      vyper2: "/vyper2",
      solidityScan: "/endpoints/solidityscan",
      embedly: "/endpoints/embedly",
      pimlico: "/endpoints/pimlico",
      ipfsGateway: "/endpoints/jqgt",
      quickdappIpfs: "/endpoints/quickdapp-ipfs",
      ensService: "/endpoints/ens-service",
      zkverify: "/endpoints/zkverify",
      ccipRead: "/endpoints/ccip-read",
      ensContractNames: "/endpoints/contract-ens",
      learneth: "/learneth",
      rss: "/endpoints/rss",
      quickdappGraph: "/endpoints/quickdapp-graph",
      notifications: "/notifications",
      feedback: "/feedback",
      walkthroughs: "/walkthroughs",
      workspaceLock: "/workspace-lock",
    },
    websockets: {
      solidityScan: "wss://api.remix.live/endpoints/solidityscan",
    },
  },
}