export const illa = {
  config: {
    openLeftPanel: true,
    mode: "edit",
    openBottomPanel: true,
    openRightPanel: true,
    openDebugger: false,
    selectedComponents: ["panel_1"],
    selectedAction: null,
    cachedAction: null,
    showDot: false,
    expandedKeys: [],
    isOnline: true,
    hoveredComponents: [],
    expandedWidgets: {},
    wsStatus: {
      DASHBOARD: "INIT",
      APP: "CONNECTED",
      APP_BINARY: "CONNECTED",
      AI_AGENT: "INIT",
    },
    draggingComponentIDs: [],
    resizingComponentIDs: [],
  },
  currentApp: {
    components: {
      root: {
        displayName: "root",
        parentNode: "",
        childrenNode: ["dock_view_1"],
        type: "DOT_PANEL",
        props: {},
      },

      dock_view_1: {
        displayName: "Dock View 1",
        parentNode: "root",
        childrenNode: ["panel_1", "panel_2", "panel_3"],
        type: "DOCK_VIEW_WIDGET",
        props: {},
      },
      panel_1: {
        displayName: "Panel 1",
        parentNode: "dock_view_1",
        childrenNode: ["button_1"],
        type: "DOCK_VIEW_PANEL_WIDGET",
        props: {
          title: "Panel 1",
          renderer: "always",
        },
      },
      panel_2: {
        displayName: "Panel 2",
        parentNode: "dock_view_1",
        childrenNode: ["button_2"],
        type: "DOCK_VIEW_PANEL_WIDGET",
        props: {
          title: 'Panel 2',
          renderer: "always",
          position: { referencePanel: "panel_1", direction: "right" },
        },
      },
      panel_3: {
        displayName: "Panel 3",
        parentNode: "dock_view_1",
        childrenNode: ["button_3"],
        type: "DOCK_VIEW_PANEL_WIDGET",
        props: {
          title: 'Panel 3',
          renderer: "always",
          position: { referencePanel: "panel_2", direction: "right" },
        },
      },

      button_1: {
        displayName: "Button 1",
        parentNode: "panel_1",
        childrenNode: [],
        type: "BUTTON_WIDGET",
        props: {
          $dynamicAttrPaths: ["text"],
          variant: "solid",
          size: "sm",
          text: "{{currentUserInfo.userID}}",
        },
      },
      button_2: {
        displayName: "Button 2",
        parentNode: "panel_2",
        childrenNode: [],
        type: "BUTTON_WIDGET",
        props: {
          $dynamicAttrPaths: ["text"],
          variant: "outline",
          size: "sm",
          text: "{{currentUserInfo.userID}}",
        },
      },
      button_3: {
        displayName: "Button 3",
        parentNode: "panel_3",
        childrenNode: [],
        type: "BUTTON_WIDGET",
        props: {
          $dynamicAttrPaths: ["text"],
          variant: "ghost",
          size: "sm",
          text: "{{currentUserInfo.userID}}",
        },
      },
    },
    action: [],
    appInfo: {
      appId: "app_dock_view_1",
      uid: "b64ff14c-3a60-4925-883a-76d85e99d619",
      teamID: "",
      appName: "app_dock_view",
      deployed: true,
      config: {
        public: false,
        waterMark: true,
        description: "",
        publishedToMarketplace: false,
        publishWithAIAgent: false,
        cover: "",
        appType: "pc",
        components: ["BUTTON_WIDGET", "DOCK_VIEW_WIDGET", "DOCK_VIEW_PANEL_WIDGET"],
        actions: [],
      },
      updatedBy: "",
      updatedAt: "",
      appActivity: {},
      editedBy: [],
    },
    collaborators: {},

    execution: {
      dependencies: {
        "button_1.text": ["currentUserInfo.userID"],
        "button_2.text": ["currentUserInfo.userID"],
        "button_3.text": ["currentUserInfo.userID"],
      },
      result: {
        root: {
          displayName: "root",
          $parentNode: "",
          $type: "WIDGET",
          $widgetType: "DOT_PANEL",
          $childrenNode: ["dock_view_1"],
        },
        dock_view_1: {
          displayName: "Dock View 1",
          $parentNode: "root",
          $type: "WIDGET",
          $widgetType: "PAGE_NODE",
          $childrenNode: ["panel_1", "panel_2", "panel_3"],
          $parentPageName: "dock_view_1",
        },
        panel_1: {
          displayName: "Panel 1",
          $parentNode: "dock_view_1",
          $type: "WIDGET",
          $widgetType: "SECTION_NODE",
          $childrenNode: [],
          $parentPageName: "page1",
        },
        panel_2: {
          displayName: "Panel 1",
          $parentNode: "dock_view_1",
          $type: "WIDGET",
          $widgetType: "SECTION_NODE",
          $childrenNode: [],
          $parentPageName: "page1",
        },
        panel_3: {
          displayName: "Panel 1",
          $parentNode: "dock_view_1",
          $type: "WIDGET",
          $widgetType: "SECTION_NODE",
          $childrenNode: [],
          $parentPageName: "page1",
        },
        button_1: {
          $dynamicAttrPaths: ["text"],
          hidden: false,
          text: "ILAfx4p1C7dZ",
          variant: "solid",
          size: "sm",
          displayName: "Button 1",
          $type: "WIDGET",
          $widgetType: "BUTTON_WIDGET",
          $parentNode: "panel_1",
          $childrenNode: [],
        },
        button_2: {
          $dynamicAttrPaths: ["text"],
          hidden: false,
          text: "ILAfx4p1C7dZ",
          variant: "solid",
          size: "sm",
          displayName: "Button 2",
          $type: "WIDGET",
          $widgetType: "BUTTON_WIDGET",
          $parentNode: "panel_2",
          $childrenNode: [],
        },
        button_3: {
          $dynamicAttrPaths: ["text"],
          hidden: false,
          text: "ILAfx4p1C7dZ",
          variant: "solid",
          size: "sm",
          displayName: "Button 3",
          $parentNode: "panel_3",
          $type: "WIDGET",
          $widgetType: "BUTTON_WIDGET",
          $childrenNode: [],
        },

        currentUserInfo: {
          userID: "ILAfx4p1C7dZ",
          nickname: "root",
          email: "root",
          language: "en-US",
          createdAt: "2025-08-20T00:20:06.088056Z",
          updatedAt: "2025-08-20T00:29:59.556997Z",
        },
        globalData: {
          $dynamicAttrPaths: [],
        },
        localStorage: {},
      },
      error: {},
      independencies: {},
    },
    cursor: {},
    dragShadow: {},
    layoutInfo: {
      widgetsLayoutInfo: {
        root: {
          displayName: "root",
          parentNode: "",
          widgetType: "DOT_PANEL",
          childrenNode: ["dock_view_1"],
          containerType: "EDITOR_DOT_PANEL",
        },

        dock_view_1: {
          displayName: "Dock View 1",
          parentNode: "root",
          childrenNode: ["panel_1", "panel_2", "panel_3"],
          widgetType: "DOCK_VIEW_WIDGET",
        },
        panel_1: {
          displayName: "Panel 1",
          parentNode: "dock_view_1",
          childrenNode: ["button_1"],
          widgetType: "DOCK_VIEW_PANEL_WIDGET",
        },
        panel_2: {
          displayName: "Panel 2",
          parentNode: "dock_view_1",
          childrenNode: ["button_2"],
          widgetType: "DOCK_VIEW_PANEL_WIDGET",
        },
        panel_3: {
          displayName: "Panel 3",
          parentNode: "dock_view_1",
          childrenNode: ["button_3"],
          widgetType: "DOCK_VIEW_PANEL_WIDGET",
        },

        button_1: {
          displayName: "Button 1",
          parentNode: "panel_1",
          childrenNode: [],
          widgetType: "BUTTON_WIDGET",
        },
        button_2: {
          displayName: "Button 2",
          parentNode: "panel_2",
          childrenNode: [],
          widgetType: "BUTTON_WIDGET",
        },
        button_3: {
          displayName: "Button 3",
          parentNode: "panel_3",
          childrenNode: [],
          widgetType: "BUTTON_WIDGET",
        },
      },
    },
  },
  currentAppHistory: {
    snapshotList: [],
    totalPages: 0,
    currentPage: 0,
    hasMore: false,
  },
  builderInfo: {
    version: "0.0.1",
    language: "English",
  },
  resource: [],
  guide: {
    currentStep: 0,
    isOpen: false,
  },
  currentUser: {
    userID: "user_id_1",
    uid: "158504d6-a47d-43a0-879e-79a57981cecc",
    nickname: "root_user",
    email: "root_user@domain.com",
    avatar: "",
    language: "en-US",
    isTutorialViewed: true,
  },
  team: {
    currentId: "current_team_id_1",
    items: [
      {
        id: "current_team_id_1",
        uid: "83cfb484-0a3f-4bfd-aab3-70432d021cab",
        name: "Team 1",
        identifier: "0",
        icon: "",
        myRole: 1,
        teamMemberID: "user_id_1",
        teamMemberPermission: {
          config: 0,
        },
        permission: {
          allowEditorInvite: true,
          allowViewerInvite: true,
          allowEditorManageTeamMember: true,
          allowViewerManageTeamMember: true,
          inviteLinkEnabled: true,
          blockRegister: false,
        },
      },
    ],
  },
  aiAgent: {
    list: [],
  },
}

export const appSmith = {
  entities: {
    canvasWidgets: {
      root: {
        widgetName: "RootContainer",
        widgetId: "root",
        type: "CANVAS_WIDGET",
        dynamicTriggerPathList: [],
        dynamicBindingPathList: [],
        children: ["dock_view_1"],
      },
      dock_view_1: {
        widgetName: "DockView1",
        widgetId: "dock_view_1",
        type: "DOCK_VIEW_WIDGET",
        dynamicTriggerPathList: [],
        dynamicBindingPathList: [],
        children: ["panel_1", "panel_2", "panel_3"],
      },
      panel_1: {
        widgetName: "Panel1",
        widgetId: "panel_1",
        type: "DOCK_VIEW_PANEL_WIDGET",
        dynamicTriggerPathList: [],
        dynamicBindingPathList: [],
        children: ["button_1"],
      },
      panel_2: {
        widgetName: "Panel2",
        widgetId: "panel_2",
        type: "DOCK_VIEW_PANEL_WIDGET",
        dynamicTriggerPathList: [],
        dynamicBindingPathList: [],
        children: ["button_2"],
      },
      panel_3: {
        widgetName: "Panel3",
        widgetId: "panel_3",
        type: "DOCK_VIEW_PANEL_WIDGET",
        dynamicTriggerPathList: [],
        dynamicBindingPathList: [],
        children: ["button_3"],
      },

      button_1: {
        widgetName: "Button1",
        widgetId: "button_1",
        type: "BUTTON_WIDGET",
        dynamicTriggerPathList: [],
        dynamicBindingPathList: [],
        variant: "solid",
        size: "sm",
        text: "Button 1 text",
      },
      button_2: {
        widgetName: "Button2",
        widgetId: "button_2",
        type: "BUTTON_WIDGET",
        dynamicTriggerPathList: [],
        dynamicBindingPathList: [
          {
            key: "text",
          },
        ],
        variant: "outline",
        size: "sm",
        text: "{{appsmith.store.var1}}",
      },
      button_3: {
        widgetName: "Button3",
        widgetId: "button_3",
        type: "BUTTON_WIDGET",
        dynamicTriggerPathList: [],
        dynamicBindingPathList: [
          {
            key: "text",
          },
        ],
        variant: "ghost",
        size: "sm",
        text: "{{appsmith.store.var2}} - with static txt",
      },
    },
    canvasWidgetsStructure: {
      widgetId: "root",
      type: "CANVAS_WIDGET",
      children: [
        {
          parentId: "root",
          widgetId: "dock_view_1",
          type: "DOCK_VIEW_WIDGET",
          children: [
            {
              parentId: "dock_view_1",
              widgetId: "panel_1",
              type: "DOCK_VIEW_PANEL_WIDGET",
              children: [
                {
                  parentId: "panel_1",
                  widgetId: "button_1",
                  type: "BUTTON_WIDGET",
                  children: [],
                },
              ],
            },
            {
              parentId: "dock_view_1",
              widgetId: "panel_2",
              type: "DOCK_VIEW_PANEL_WIDGET",
              children: [
                {
                  parentId: "panel_2",
                  widgetId: "button_2",
                  type: "BUTTON_WIDGET",
                  children: [],
                },
              ],
            },
            {
              parentId: "dock_view_1",
              widgetId: "panel_3",
              type: "DOCK_VIEW_PANEL_WIDGET",
              children: [
                {
                  parentId: "panel_3",
                  widgetId: "button_3",
                  type: "BUTTON_WIDGET",
                  children: [],
                },
              ],
            },
          ],
        },
      ],
    },
    metaWidgets: {},
    actions: [],
    datasources: {},
    pageList: {
      pages: [
        {
          pageName: "Dock View Page 1",
          pageId: "page_id_1",
          basePageId: "page_id_1",
          isDefault: true,
          isHidden: false,
          slug: "page_id_1",
          userPermissions: [],
        },
      ],
      isGeneratingTemplatePage: false,
      generatePage: {
        modalOpen: false,
        params: {},
      },
      baseApplicationId: "app_dock_view_1",
      applicationId: "app_dock_view_1",
      currentBasePageId: "page_id_1",
      currentPageId: "page_id_1",
      defaultBasePageId: "page_id_1",
      defaultPageId: "page_id_1",
      loading: {},
    },
    plugins: {
      list: [
        {
          id: "id_restapi_plugin",
          userPermissions: [],
          name: "REST API",
          type: "API",
          packageName: "restapi-plugin",
          iconLocation: "",
          documentationLink: "",
          uiComponent: "ApiEditorForm",
          datasourceComponent: "RestAPIDatasourceForm",
          allowUserDatasources: true,
          isRemotePlugin: false,
          templates: {},
          remotePlugin: false,
        },
      ],
      defaultPluginList: [
        {
          id: "id_restapi_plugin",
          userPermissions: [],
          name: "REST API",
          packageName: "restapi-plugin",
          iconLocation: "",
          allowUserDatasources: true,
          isRemotePlugin: false,
          remotePlugin: false,
        },
      ],
      loading: false,
      formConfigs: {
        id_restapi_plugin: [
          {
            sectionName: "General",
            children: [
              {
                label: "URL",
                configProperty: "datasourceConfiguration.url",
                controlType: "INPUT_TEXT",
                isRequired: true,
                placeholderText: "https://example.com",
              },
            ],
          },
        ],
      },
      editorConfigs: {
        id_restapi_plugin: [
          {
            sectionName: "",
            id: 1,
            children: [
              {
                label: "Path",
                configProperty: "actionConfiguration.path",
                controlType: "QUERY_DYNAMIC_INPUT_TEXT",
              },
              {
                label: "Body",
                configProperty: "actionConfiguration.body",
                controlType: "QUERY_DYNAMIC_INPUT_TEXT",
                evaluationSubstitutionType: "SMART_SUBSTITUTE",
                hidden: {
                  path: "actionConfiguration.pluginSpecifiedTemplates[0].value",
                  comparison: "EQUALS",
                  value: false,
                },
              },
              {
                label: "Body",
                configProperty: "actionConfiguration.body",
                controlType: "QUERY_DYNAMIC_INPUT_TEXT",
                evaluationSubstitutionType: "TEMPLATE",
                hidden: {
                  path: "actionConfiguration.pluginSpecifiedTemplates[0].value",
                  comparison: "EQUALS",
                  value: true,
                },
              },
              {
                label: "Query parameters",
                configProperty: "actionConfiguration.queryParameters",
                controlType: "ARRAY_FIELD",
                schema: [
                  {
                    label: "Key",
                    key: "key",
                    controlType: "QUERY_DYNAMIC_INPUT_TEXT",
                    placeholderText: "Key",
                  },
                  {
                    label: "Value",
                    key: "value",
                    controlType: "QUERY_DYNAMIC_INPUT_TEXT",
                    placeholderText: "Value",
                  },
                ],
              },
              {
                label: "Headers",
                configProperty: "actionConfiguration.headers",
                controlType: "ARRAY_FIELD",
                schema: [
                  {
                    label: "Key",
                    key: "key",
                    controlType: "QUERY_DYNAMIC_INPUT_TEXT",
                    placeholderText: "Key",
                  },
                  {
                    label: "Value",
                    key: "value",
                    controlType: "QUERY_DYNAMIC_INPUT_TEXT",
                    placeholderText: "Value",
                  },
                ],
              },
              {
                label: "Form data",
                configProperty: "actionConfiguration.bodyFormData",
                controlType: "ARRAY_FIELD",
                schema: [
                  {
                    label: "Key",
                    key: "key",
                    controlType: "QUERY_DYNAMIC_INPUT_TEXT",
                    placeholderText: "Key",
                  },
                  {
                    label: "Value",
                    key: "value",
                    controlType: "QUERY_DYNAMIC_INPUT_TEXT",
                    placeholderText: "Value",
                  },
                ],
              },
              {
                label: "Query variables",
                configProperty: "actionConfiguration.pluginSpecifiedTemplates[1].value",
                controlType: "QUERY_DYNAMIC_INPUT_TEXT",
                evaluationSubstitutionType: "SMART_SUBSTITUTE",
                hidden: {
                  path: "actionConfiguration.pluginSpecifiedTemplates[0].value",
                  comparison: "EQUALS",
                  value: false,
                },
              },
              {
                label: "Query variables",
                configProperty: "actionConfiguration.pluginSpecifiedTemplates[1].value",
                controlType: "QUERY_DYNAMIC_INPUT_TEXT",
                evaluationSubstitutionType: "TEMPLATE",
                hidden: {
                  path: "actionConfiguration.pluginSpecifiedTemplates[0].value",
                  comparison: "EQUALS",
                  value: true,
                },
              },
              {
                label: "Pagination",
                configProperty: "actionConfiguration.pluginSpecifiedTemplates[2].value",
                controlType: "E_GRAPHQL_PAGINATION",
                evaluationSubstitutionType: "SMART_SUBSTITUTE",
              },
            ],
          },
        ],
      },
      settingConfigs: {
        id_restapi_plugin: [
          {
            sectionName: "",
            id: 1,
            children: [
              {
                label: "Run behavior",
                configProperty: "runBehaviour",
                controlType: "DROP_DOWN",
                initialValue: "MANUAL",
                options: [
                  {
                    label: "Automatic",
                    subText: "Query runs on page load or when a variable it depends on changes",
                    value: "AUTOMATIC",
                    children: "Automatic",
                  },
                  {
                    label: "On page load",
                    subText: "Query runs when the page loads or when manually triggered",
                    value: "ON_PAGE_LOAD",
                    children: "On page load",
                  },
                  {
                    label: "Manual",
                    subText: "Query only runs when called in an event or JS with .run()",
                    value: "MANUAL",
                    children: "Manual",
                  },
                ],
              },
              {
                label: "Request confirmation before running this API",
                configProperty: "confirmBeforeExecute",
                controlType: "SWITCH",
                tooltipText: "Ask confirmation from the user each time before refreshing data",
              },
              {
                label: "Encode query params",
                configProperty: "actionConfiguration.encodeParamsToggle",
                controlType: "SWITCH",
                tooltipText:
                  "Encode query params for all APIs. Also encode form body when Content-Type header is set to x-www-form-encoded",
              },
              {
                label: "Smart JSON substitution",
                configProperty: "actionConfiguration.pluginSpecifiedTemplates[0].value",
                controlType: "SWITCH",
                tooltipText:
                  "Turning on this property fixes the JSON substitution of bindings in API body by adding/removing quotes intelligently and reduces developer errors",
                initialValue: true,
              },
              {
                label: "Protocol",
                configProperty: "actionConfiguration.httpVersion",
                name: "actionConfiguration.httpVersion",
                controlType: "DROP_DOWN",
                initialValue: "HTTP/1.1",
                options: [
                  {
                    label: "HTTP/1.1",
                    value: "HTTP11",
                  },
                  {
                    label: "HTTP/2",
                    value: "H2",
                  },
                  {
                    label: "H2C",
                    value: "H2C",
                  },
                ],
                placeholder: "Select HTTP Protocol",
              },
              {
                label: "API timeout (in milliseconds)",
                subtitle: "Maximum time after which the API will return",
                controlType: "INPUT_TEXT",
                configProperty: "actionConfiguration.timeoutInMillisecond",
                dataType: "NUMBER",
              },
            ],
          },
        ],
      },
      datasourceFormButtonConfigs: {
        id_restapi_plugin: ["CANCEL", "SAVE"],
      },
      dependencies: {
        id_restapi_plugin: {
          "actionConfiguration.body": ["actionConfiguration.pluginSpecifiedTemplates[0].value"],
        },
      },
      fetchingSinglePluginForm: {},
      fetchingDefaultPlugins: false,
    },
    meta: {},
    app: {
      user: {},
      URL: {
        fullPath: "",
        host: "",
        hostname: "",
        queryParams: {},
        protocol: "https:",
        pathname: "",
        port: "",
        hash: "",
      },
      store: {
        var1: "Dynamic binding var 1",
        var2: "Dynamic binding var 2",
      },
      geolocation: {
        canBeRequested: true,
        currentPosition: {},
      },
      workflows: {},
      mode: "EDIT",
    },
    jsActions: [],
    autoHeightLayoutTree: {},
    canvasLevels: {},
    layoutElementPositions: {},
    moduleInstanceEntities: {},
  },
  ui: {
    analytics: {},
    editor: {
      initialized: true,
      loadingStates: {
        saving: false,
        savingError: false,
        loading: false,
        loadingError: false,
      },
      currentLayoutId: "dock_view_1_layout",
    },
    errors: {},
    propertyPane: {
      isVisible: false,
      isNew: false,
      selectedPropertyPanel: {},
    },
    tableFilterPane: {
      isVisible: false,
    },
    appView: {
      isFetchingPage: false,
      initialized: false,
    },
    applications: {
      applicationList: [],
      creatingApplication: {},
      deletingApplication: false,
      forkingApplication: false,
      importingApplication: false,
      importedApplication: null,
      loadingStates: {
        isFetchingAllRoles: false,
        isFetchingAllUsers: false,
      },
      currentApplication: {
        applicationDetail: {},
        id: "app_dock_view_1",
        name: "",
        slug: "",
        artifactType: "APPLICATION",
        pages: [],
        baseId: "app_dock_view_1",
      },
    },
    auth: {
      isValidatingToken: true,
      isTokenValid: false,
    },
    templates: {
      isImportingTemplate: false,
      loadingFilters: false,
      activeTemplate: null,
      activeLoadingTemplateId: null,
      templates: [],
      similarTemplates: [],
      filter: [],
      templateSearchQuery: "",
    },
    buildingBlocks: {
      isDraggingBuildingBlocksToCanvas: false,
    },
    workspaces: {
      loadingStates: {
        isFetchAllRoles: false,
        isSavingWorkspaceInfo: false,
        isFetchingWorkspaces: false,
        isFetchingEntities: false,
        isDeletingWorkspace: false,
      },
      list: [],
      workspaceRoles: [],
      searchEntities: {},
    },
    selectedWorkspace: {
      workspace: {},
      applications: [],
      users: [],
      packages: [],
      loadingStates: {
        isFetchingApplications: false,
        isFetchingAllUsers: false,
        isFetchingCurrentWorkspace: false,
      },
    },
    users: {
      loadingStates: {
        fetchingUsers: false,
        fetchingUser: false,
      },
      list: [],
      users: [],
      error: "",
      currentUser: {
        email: "",
        username: "",
        name: "",
      },
      featureFlag: {
        data: {},
        isFetched: true,
        isFetching: false,
        overriddenFlags: {},
        productAlert: {},
      },
    },
    widgetDragResize: {
      isDragging: false,
      lastSelectedWidget: "ydlupoo8k2",
      selectedWidgets: [],
      isDraggingDisabled: false,
    },
    imports: {
      isImportingCurl: false,
      errorPayload: {},
    },
    datasourcePane: {
      drafts: {},
      newDatasource: "",
      viewMode: true,
      defaultKeyValueArrayConfig: [],
    },
    datasourceName: {
      isSaving: {},
      errors: {},
    },
    help: {},
    apiName: {
      isSaving: {},
      errors: {},
    },
    explorer: {
      entity: {},
      active: true,
    },
    pageCanvasStructure: {
      page_id_1: {
        widgetId: "root",
        type: "CANVAS_WIDGET",
        children: [
          {
            parentId: "root",
            widgetId: "dock_view_1",
            type: "DOCK_VIEW_WIDGET",
            children: [
              {
                parentId: "dock_view_1",
                widgetId: "panel_1",
                type: "DOCK_VIEW_PANEL_WIDGET",
                children: [
                  {
                    parentId: "panel_1",
                    widgetId: "button_1",
                    type: "BUTTON_WIDGET",
                    children: [],
                  },
                ],
              },
              {
                parentId: "dock_view_1",
                widgetId: "panel_2",
                type: "DOCK_VIEW_PANEL_WIDGET",
                children: [
                  {
                    parentId: "panel_2",
                    widgetId: "button_2",
                    type: "BUTTON_WIDGET",
                    children: [],
                  },
                ],
              },
              {
                parentId: "dock_view_1",
                widgetId: "panel_3",
                type: "DOCK_VIEW_PANEL_WIDGET",
                children: [
                  {
                    parentId: "panel_3",
                    widgetId: "button_3",
                    type: "BUTTON_WIDGET",
                    children: [],
                  },
                ],
              },
            ],
          },
        ],
      },
    },
    pageWidgets: {
      page_id_1: {
        dsl: {
          root: {
            widgetName: "Root Container",
            widgetId: "root",
            type: "CANVAS_WIDGET",
            dynamicTriggerPathList: [],
            dynamicBindingPathList: [],
            children: ["dock_view_1"],
          },
          dock_view_1: {
            widgetName: "Dock View 1",
            widgetId: "dock_view_1",
            type: "DOCK_VIEW_WIDGET",
            dynamicTriggerPathList: [],
            dynamicBindingPathList: [],
            children: ["panel_1", "panel_2", "panel_3"],
          },
          panel_1: {
            widgetName: "Panel 1",
            widgetId: "panel_1",
            type: "DOCK_VIEW_PANEL_WIDGET",
            dynamicTriggerPathList: [],
            dynamicBindingPathList: [],
            children: ["button_1"],
          },
          panel_2: {
            widgetName: "Panel 2",
            widgetId: "panel_2",
            type: "DOCK_VIEW_PANEL_WIDGET",
            dynamicTriggerPathList: [],
            dynamicBindingPathList: [],
            children: ["button_2"],
          },
          panel_3: {
            widgetName: "Panel 3",
            widgetId: "panel_3",
            type: "DOCK_VIEW_PANEL_WIDGET",
            dynamicTriggerPathList: [],
            dynamicBindingPathList: [],
            children: ["button_3"],
          },

          button_1: {
            widgetName: "Button 1",
            widgetId: "button_1",
            type: "BUTTON_WIDGET",
            dynamicTriggerPathList: [],
            dynamicBindingPathList: [],
            variant: "solid",
            size: "sm",
            text: "Button 1 text",
          },
          button_2: {
            widgetName: "Button 2",
            widgetId: "button_2",
            type: "BUTTON_WIDGET",
            dynamicTriggerPathList: [],
            dynamicBindingPathList: [
              {
                key: "text",
              },
            ],
            variant: "outline",
            size: "sm",
            text: "{{appsmith.store.var1}}",
          },
          button_3: {
            widgetName: "Button 3",
            widgetId: "button_3",
            type: "BUTTON_WIDGET",
            dynamicTriggerPathList: [],
            dynamicBindingPathList: [
              {
                key: "text",
              },
            ],
            variant: "ghost",
            size: "sm",
            text: "Button3 text: {{appsmith.store.var2}}",
          },
        },
        layoutId: "dock_view_1_layout",
      },
    },
    theme: {
      mode: "LIGHT",
      theme: {},
    },
    modalAction: {
      modals: [],
    },
    onBoarding: {
      firstTimeUserOnboardingApplicationIds: [],
      firstTimeUserOnboardingComplete: false,
      showFirstTimeUserOnboardingModal: false,
      stepState: [],
      showSignpostingTooltip: false,
      showAnonymousDataPopup: false,
    },
    globalSearch: {
      query: "",
      recentEntities: [],
      filterContext: {},
    },
    releases: {
      newReleasesCount: "",
      releaseItems: [],
    },
    debugger: {
      logs: [
        {
          text: "storeValue triggered",
          state: {
            key: "var2",
            value: "Dynamic Left: STATIC text from Left Container",
            persist: true,
          },
          severity: "info",
          category: "PLATFORM_GENERATED",
          timestamp: "1756646993658",
          isExpanded: false,
        },
      ],
      isOpen: false,
      errors: {},
      expandId: "",
      hideErrors: false,
      context: {
        selectedDebuggerTab: "",
        errorCount: 0,
        selectedDebuggerFilter: "",
      },
      stateInspector: {},
    },
    tour: {
      isTourInProgress: false,
      activeTourIndex: -1,
    },
    jsPane: {
      isCreating: false,
      isSaving: {},
      isDeleting: {},
      isDirty: {},
      isSchemaGenerating: {},
      selectedConfigTab: "CODE",
      debugger: {
        open: false,
      },
      isFetching: false,
    },
    jsObjectName: {
      isSaving: {},
      errors: {},
    },
    canvasSelection: {
      isDraggingForSelection: false,
      widgetId: "",
      recentlyAddedWidget: {},
    },
    gitSync: {},
    crudInfoModal: {
      crudInfoModalOpen: false,
      generateCRUDSuccessInfo: null,
    },
    widgetReflow: {
      isReflowing: false,
      reflowingWidgets: {},
    },
    appTheming: {
      stack: [],
      themes: [
        {
          id: "",
          userPermissions: [],
          name: "Default-New",
          displayName: "Modern",
          config: {
            colors: {},
            borderRadius: {},
            boxShadow: {},
            fontFamily: {},
          },
          properties: {
            colors: {},
            borderRadius: {},
            boxShadow: {},
            fontFamily: {},
          },
          isSystemTheme: true,
        },
      ],
      isSaving: false,
      isChanging: false,
      themesLoading: false,
      selectedThemeLoading: false,
      selectedTheme: {},
    },
    mainCanvas: {
      initialized: true,
    },
    appSettingsPane: {
      isOpen: false,
    },
    focusHistory: {
      history: {
        "PAGE.page_id_1": {
          entityInfo: {
            id: "PAGE.page_id_1",
            appState: "EDITOR",
            entity: "PAGE",
            params: {},
          },
          state: {
            CodeEditorHistory: {},
          },
        },
      },
    },
    editorContext: {
      codeEditorHistory: {},
      propertySectionState: {},
      selectedPropertyTabIndex: 0,
      propertyPanelState: {},
      entityCollapsibleFields: {},
      subEntityCollapsibleFields: {},
      explorerSwitchIndex: 0,
    },
    libraries: {
      isInstallerOpen: false,
      installationStatus: {},
      installedLibraries: [
        {
          name: "lodash",
          docsURL: "https://lodash.com/docs/4.17.21",
          version: "4.17.21",
          accessor: ["_"],
        },
        {
          name: "moment",
          docsURL: "https://momentjs.com/docs/",
          version: "0.5.35",
          accessor: ["moment"],
        },
        {
          name: "forge",
          docsURL: "https://github.com/digitalbazaar/forge",
          version: "1.3.0",
          accessor: ["forge"],
        },
      ],
      reservedNames: [],
    },
    autoHeightUI: {},
    layoutConversion: {
      snapshotDetails: {
        updatedTime: null,
      },
      conversionState: "START",
      isConverting: false,
    },
    actionSelector: {},
    oneClickBinding: {
      isConnecting: false,
      config: null,
      showOptions: false,
    },
    activeField: null,
    ide: {
      view: "SplitScreen",
      tabs: {},
      isListViewActive: false,
      showCreateModal: false,
      renameEntity: "",
      ideCanvasSideBySideHover: {
        navigated: false,
        widgetTypes: [],
      },
    },
    consolidatedPageLoad: {
      isLoading: false,
    },
    pluginActionEditor: {
      isCreating: false,
      isRunning: {},
      isSaving: {},
      isSchemaGenerating: {},
      isDeleting: {},
      isDirty: {},
      runErrorMessage: {},
      debugger: {
        open: false,
      },
      settingsOpen: false,
    },
  },
  evaluations: {
    tree: {
      RootContainer: {
        ENTITY_TYPE: "WIDGET",
        widgetName: "RootContainer",
        widgetId: "root",
        canExtend: true,
        meta: {},
        isLoading: false,
        type: "CANVAS_WIDGET",
        backgroundColor: "none",
        borderColor: "",
        borderRadius: "",
        boxShadow: "",
        __evaluation__: {
          errors: {
            isVisible: [],
            animateLoading: [],
            backgroundColor: [],
            borderColor: [],
            borderWidth: [],
            borderRadius: [],
            boxShadow: [],
          },
        },
      },
      DockView1: {
        ENTITY_TYPE: "WIDGET",
        widgetName: "DockView1",
        widgetId: "dock_view_1",
        canExtend: false,
        isVisible: true,
        isLoading: false,
        meta: {},
        type: "CANVAS_WIDGET",
        backgroundColor: "",
        borderColor: "",
        __evaluation__: {
          errors: {
            boxShadow: [],
            borderRadius: [],
            isVisible: [],
            animateLoading: [],
            backgroundColor: [],
            borderColor: [],
            borderWidth: [],
          },
        },
      },
      Panel1: {
        ENTITY_TYPE: "WIDGET",
        needsErrorInfo: false,
        widgetName: "Panel1",
        canExtend: false,
        widgetId: "panel_1",
        isVisible: true,
        isLoading: false,
        meta: {},
        type: "CANVAS_WIDGET",
        backgroundColor: "",
        borderColor: "",
        __evaluation__: {
          errors: {
            boxShadow: [],
            borderRadius: [],
            isVisible: [],
            animateLoading: [],
            backgroundColor: [],
            borderColor: [],
            borderWidth: [],
          },
        },
      },
      Panel2: {
        ENTITY_TYPE: "WIDGET",
        needsErrorInfo: false,
        widgetName: "Panel2",
        canExtend: false,
        widgetId: "panel_2",
        isVisible: true,
        isLoading: false,
        meta: {},
        type: "CANVAS_WIDGET",
        backgroundColor: "",
        borderColor: "",
        __evaluation__: {
          errors: {
            boxShadow: [],
            borderRadius: [],
            isVisible: [],
            animateLoading: [],
            backgroundColor: [],
            borderColor: [],
            borderWidth: [],
          },
        },
      },
      Panel3: {
        ENTITY_TYPE: "WIDGET",
        needsErrorInfo: false,
        widgetName: "Panel3",
        canExtend: false,
        widgetId: "panel_3",
        isVisible: true,
        isLoading: false,
        meta: {},
        type: "CANVAS_WIDGET",
        backgroundColor: "",
        borderColor: "",
        __evaluation__: {
          errors: {
            boxShadow: [],
            borderRadius: [],
            isVisible: [],
            animateLoading: [],
            backgroundColor: [],
            borderColor: [],
            borderWidth: [],
          },
        },
      },
      Button1: {
        ENTITY_TYPE: "WIDGET",
        resetFormOnClick: false,
        needsErrorInfo: false,
        widgetName: "Button1",
        onClick: "",
        text: "Button 1 text",
        isDisabled: false,
        isDefaultClickDisabled: true,
        widgetId: "button_1",
        isVisible: true,
        isLoading: false,
        disabledWhenInvalid: false,
        meta: {},
        type: "BUTTON_WIDGET",
        tooltip: "",
        iconName: "",
        __evaluation__: {
          errors: {
            borderRadius: [],
            buttonColor: [],
            onClick: [],
            text: [],
            tooltip: [],
            isVisible: [],
            isDisabled: [],
            animateLoading: [],
            googleRecaptchaKey: [],
            recaptchaType: [],
            disabledWhenInvalid: [],
            resetFormOnClick: [],
            buttonVariant: [],
            iconName: [],
            placement: [],
            boxShadow: [],
          },
        },
      },
      Button2: {
        ENTITY_TYPE: "WIDGET",
        resetFormOnClick: false,
        needsErrorInfo: false,
        widgetName: "Button2",
        onClick: "",
        text: "Button 2",
        isDisabled: false,
        isDefaultClickDisabled: true,
        widgetId: "button_2",
        isVisible: true,
        isLoading: false,
        disabledWhenInvalid: false,
        meta: {},
        type: "BUTTON_WIDGET",
        tooltip: "",
        iconName: "",
        __evaluation__: {
          errors: {
            borderRadius: [],
            buttonColor: [],
            onClick: [],
            text: [],
            tooltip: [],
            isVisible: [],
            isDisabled: [],
            animateLoading: [],
            googleRecaptchaKey: [],
            recaptchaType: [],
            disabledWhenInvalid: [],
            resetFormOnClick: [],
            buttonVariant: [],
            iconName: [],
            placement: [],
            boxShadow: [],
          },
        },
      },
      Button3: {
        ENTITY_TYPE: "WIDGET",
        resetFormOnClick: false,
        needsErrorInfo: false,
        widgetName: "Button3",
        onClick: "",
        text: "Button 3",
        isDisabled: false,
        isDefaultClickDisabled: true,
        widgetId: "button_3",
        isVisible: true,
        isLoading: false,
        disabledWhenInvalid: false,
        meta: {},
        type: "BUTTON_WIDGET",
        tooltip: "",
        iconName: "",
        __evaluation__: {
          errors: {
            borderRadius: [],
            buttonColor: [],
            onClick: [],
            text: [],
            tooltip: [],
            isVisible: [],
            isDisabled: [],
            animateLoading: [],
            googleRecaptchaKey: [],
            recaptchaType: [],
            disabledWhenInvalid: [],
            resetFormOnClick: [],
            buttonVariant: [],
            iconName: [],
            placement: [],
            boxShadow: [],
          },
        },
      },
      internal: {
        user: {
          email: "",
          username: "",
          name: "",
          useCase: "",
          enableTelemetry: true,
          roles: [],
          groups: [],
          accountNonExpired: true,
          accountNonLocked: true,
          credentialsNonExpired: true,
          emptyInstance: false,
          isAnonymous: false,
          isEnabled: true,
          isSuperUser: true,
          isConfigurable: true,
          adminSettingsVisible: false,
          isIntercomConsentGiven: false,
        },
        URL: {
          fullPath: "",
          host: "",
          hostname: "",
          queryParams: {},
          protocol: ":",
          pathname: "",
          port: "",
          hash: "",
        },
        store: {
          var1: "Dynamic Left: STATIC text from Right Container",
          var2: "Dynamic Right: STATIC text from Left Container",
        },
        geolocation: {
          canBeRequested: true,
          currentPosition: {},
        },
        workflows: {},
        mode: "EDIT",
        theme: {
          colors: {},
          borderRadius: {},
          boxShadow: {},
          fontFamily: {},
        },
        currentPageName: "",
        workspaceName: "",
        appName: "",
        currentEnvironmentName: "",
        ENTITY_TYPE: "",
      },
    },
    dependencies: {
      inverseDependencyMap: {
        "internal.store.var2": ["button_3.text", "internal.store"],
        "button_3.text": ["button_3"],
        "internal.store.var1": ["button_2.text", "internal.store"],
        "button_2.text": ["button_2"],
        "internal.store": ["internal"],
      },
    },
    loadingEntities: {},
    formEvaluation: {},
    triggers: {},
    firstEvaluation: {
      renderPage: true,
      isFirstPageLoad: true,
    },
  },
  form: {},
  settings: {
    isLoading: false,
    isSaving: false,
    isRestarting: false,
    showReleaseNotes: false,
    isRestartFailed: false,
    config: {
      instanceName: "AppInstance",
      googleMapsKey: "",
      emailVerificationEnabled: false,
      isAtomicPushAllowed: false,
      isFormLoginEnabled: true,
      isSignupDisabled: false,
    },
  },
  organization: {
    userPermissions: [],
    organizationConfiguration: {
      brandFaviconUrl: "",
      brandColors: {},
      brandLogoUrl: "",
      googleMapsKey: "",
      isFormLoginEnabled: true,
      isSignupDisabled: false,
      instanceName: "AppInstance",
      license: {
        plan: "FREE",
      },
      emailVerificationEnabled: false,
      thirdPartyAuths: null,
      migrationStatus: "COMPLETED",
      featuresWithPendingMigration: {},
      isAtomicPushAllowed: false,
    },
    new: false,
    isLoading: false,
    instanceId: "instance_id",
    tenantId: "tenant_id",
    myOrganizations: [],
    isFetchingMyOrganizations: false,
  },
  linting: {
    errors: {},
  },
  git: {
    artifacts: {
      applications: {
        app_dock_view_1: {
          ui: {
            initializing: false,
            initialized: true,
            currentBranch: null,
            connectModalOpen: false,
            connectSuccessModalOpen: false,
            disconnectBaseArtifactId: null,
            disconnectArtifactType: null,
            disconnectArtifactName: null,
            branchPopupOpen: false,
            checkoutDestBranch: null,
            opsModalOpen: false,
            opsModalTab: "Deploy",
            mergeSuccess: false,
            settingsModalOpen: false,
            settingsModalTab: "General",
            autocommitDisableModalOpen: false,
            autocommitPolling: false,
            conflictErrorModalOpen: false,
          },
          apiResponses: {
            metadata: {
              value: null,
              loading: false,
              error: null,
            },
            connect: {
              loading: false,
              error: null,
            },
            status: {
              value: null,
              loading: false,
              error: null,
            },
            commit: {
              loading: false,
              error: null,
            },
            pull: {
              loading: false,
              error: null,
            },
            discard: {
              loading: false,
              error: null,
            },
            mergeStatus: {
              value: null,
              loading: false,
              error: null,
            },
            merge: {
              loading: false,
              error: null,
            },
            branches: {
              value: null,
              loading: false,
              error: null,
            },
            checkoutBranch: {
              loading: false,
              error: null,
            },
            createBranch: {
              loading: false,
              error: null,
            },
            deleteBranch: {
              loading: false,
              error: null,
            },
            localProfile: {
              value: null,
              loading: false,
              error: null,
            },
            updateLocalProfile: {
              loading: false,
              error: null,
            },
            disconnect: {
              loading: false,
              error: null,
            },
            protectedBranches: {
              value: null,
              loading: false,
              error: null,
            },
            updateProtectedBranches: {
              loading: false,
              error: null,
            },
            autocommitProgress: {
              loading: false,
              error: null,
            },
            toggleAutocommit: {
              loading: false,
              error: null,
            },
            triggerAutocommit: {
              loading: false,
              error: null,
            },
            generateSSHKey: {
              loading: false,
              error: null,
            },
            sshKey: {
              value: null,
              loading: false,
              error: null,
            },
            pretag: {
              value: null,
              loading: false,
              error: null,
            },
            createReleaseTag: {
              loading: false,
              error: null,
            },
          },
        },
      },
    },
    global: {
      globalProfile: {
        value: null,
        loading: false,
        error: null,
      },
      updateGlobalProfile: {
        loading: false,
        error: null,
      },
      globalSSHKey: {
        value: null,
        loading: false,
        error: null,
      },
      gitImport: {
        loading: false,
        error: null,
      },
      isImportModalOpen: false,
      importOverrideDetails: null,
      repoLimitErrorModalOpen: false,
    },
  },
}
